In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import cv2
import json

In [2]:
df = pd.read_json("scout_car.json", lines=True)
df

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,...,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,VAT deductible,"56,013 km",01/2016,2 previous owners,NaN,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.8 TFSI sport,Sedans,14500,Price negotiable,"80,000 km",03/2017,None,NaN,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,VAT deductible,"83,450 km",02/2016,1 previous owner,NaN,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.4 TDi Design S tronic,Sedans,14500,None,"73,000 km",08/2016,1 previous owner,NaN,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,"16,200 km",05/2016,1 previous owner,NaN,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [748]:
df.shape

(15919, 54)

In [749]:
df.head(5).T

,0,1,2,3,4
url,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1
short_description,Sportback 1.4 TDI S-tronic Xenon Navi Klima,1.8 TFSI sport,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,1.4 TDi Design S tronic,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...
body_type,Sedans,Sedans,Sedans,Sedans,Sedans
price,15770,14500,14640,14500,16790
vat,VAT deductible,Price negotiable,VAT deductible,None,None
km,"56,013 km","80,000 km","83,450 km","73,000 km","16,200 km"
registration,01/2016,03/2017,02/2016,08/2016,05/2016
prev_owner,2 previous owners,None,1 previous owner,1 previous owner,1 previous owner
kW,NaN,NaN,NaN,NaN,NaN
hp,66 kW,141 kW,85 kW,66 kW,66 kW
Type,"[, Used, , Diesel (Particulate Filter)]","[, Used, , Gasoline]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]"
Previous Owners,\n2\n,NaN,\n1\n,\n1\n,\n1\n
Next Inspection,"[\n06/2021\n, \n99 g CO2/km (comb)\n]",NaN,NaN,NaN,NaN
Inspection new,"[\nYes\n, \nEuro 6\n]",NaN,NaN,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]"
Warranty,"[\n, \n, \n4 (Green)\n]",NaN,"[\n, \n, \n99 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]"
Full Service,"[\n, \n]",NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]","[\n, \n, \n4 (Green)\n]"
Non-smoking Vehicle,"[\n, \n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n]"
null,[],[],[],[],[]
Make,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n
Model,"[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]"
Offer Number,[\nLR-062483\n],NaN,[\nAM-95365\n],NaN,[\nC1626\n]
First Registration,"[\n, 2016, \n]","[\n, 2017, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]"
Body Color,"[\n, Black, \n]","[\n, Red, \n]","[\n, Black, \n]","[\n, Brown, \n]","[\n, Black, \n]"
Paint Type,[\nMetallic\n],NaN,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n]
Body Color Original,[\nMythosschwarz\n],NaN,[\nmythosschwarz metallic\n],NaN,[\nMythosschwarz Metallic\n]
Upholstery,"[\nCloth, Black\n]","[\nCloth, Grey\n]","[\nCloth, Black\n]",NaN,"[\nCloth, Black\n]"
Body,"[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]"
Nr. of Doors,[\n5\n],[\n3\n],[\n4\n],[\n3\n],[\n5\n]
Nr. of Seats,[\n5\n],[\n4\n],[\n4\n],[\n4\n],[\n5\n]
Model Code,[\n0588/BDF\n],[\n0588/BCY\n],NaN,NaN,[\n0588/BDF\n]
Gearing Type,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]"
Displacement,"[\n1,422 cc\n]","[\n1,798 cc\n]","[\n1,598 cc\n]","[\n1,422 cc\n]","[\n1,422 cc\n]"
Cylinders,[\n3\n],[\n4\n],NaN,[\n3\n],[\n3\n]
Weight,"[\n1,220 kg\n]","[\n1,255 kg\n]",NaN,"[\n1,195 kg\n]",NaN
Drive chain,[\nfront\n],[\nfront\n],[\nfront\n],NaN,[\nfront\n]
Fuel,"[\n, Diesel (Particulate Filter), \n]","[\n, Gasoline, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]"
Consumption,"[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[5.6 l/100 km (comb)], [7.1 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.4 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[4.1 l/100 km (comb)], [4.6 l/100 km (city)],..."
CO2 Emission,[\n99 g CO2/km (comb)\n],[\n129 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n109 g CO2/km (comb)\n]
Emission Class,[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n]
\nComfort & Convenience\n,"[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Cruise control, Electrical ...","[Air suspension, Armrest, Auxiliary heating, E...","[Air conditioning, Armrest, Automatic climate ..."
\nEntertainment & Media\n,"[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Hands-free equipment, On-board com...","[MP3, On-board computer]","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M..."
\nExtras\n,"[Alloy wheels, Catalytic Converter, Voice Cont...","[Alloy wheels, Sport seats, Sport suspension, ...","[Alloy wheels, Voice Control]","[Alloy wheels, Sport seats, Voice Control]","[Alloy wheels, Sport package, Sport suspension..."
\nSafety & Security\n,"[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Central door lock wit...","[ABS, Central door lock, Daytime running light...","[ABS, Alarm system, Central door lock with rem...","[ABS, Central door lock, Driver-side airbag, E..."
description,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",[\nLangstreckenfahrzeug daher die hohe Kilomet...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...","[\nAudi A1: , - 1e eigenaar , - Perfecte staat...","[\n, Technik & Sicherheit:, Xenon plus, Klimaa..."
Emission Label,NaN,[\n4 (Green)\n],[\n4 (Green)\n],NaN,NaN
Gears,NaN,[\n7\n],NaN,[\n6\n],NaN
Country version,NaN,NaN,NaN,NaN,[\nGermany\n]
Electricity consumption,NaN,NaN,NaN,NaN,NaN
Last Service Date,NaN,NaN,NaN,NaN,NaN
Other Fuel Types,NaN,NaN,NaN,NaN,NaN
Availability,NaN,NaN,NaN,NaN,NaN
Last Timing Belt Service Date,NaN,NaN,NaN,NaN,NaN
Available from,NaN,NaN,NaN,NaN,NaN

In [750]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  Type                           15917 non-null  object
 12  Previous Owners                9279 non-null   object
 13  Next Inspection                3535 non-null   object
 14  Inspection new                 3932 non-null   object
 15  Warranty                       10499 non-null  object
 16  Full Service                   8215 non-null   object
 17  Non-smoking Vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  Make                           15919 non-null  object
 20  Model                          15919 non-null  object
 21  Offer Number                   12744 non-null  object
 22  First Registration             14322 non-null  object
 23  Body Color                     15322 non-null  object
 24  Paint Type                     10147 non-null  object
 25  Body Color Original            12160 non-null  object
 26  Upholstery                     12199 non-null  object
 27  Body                           15859 non-null  object
 28  Nr. of Doors                   15707 non-null  object
 29  Nr. of Seats                   14942 non-null  object
 30  Model Code                     4978 non-null   object
 31  Gearing Type                   15919 non-null  object
 32  Displacement                   15423 non-null  object
 33  Cylinders                      10239 non-null  object
 34  Weight                         8945 non-null   object
 35  Drive chain                    9061 non-null   object
 36  Fuel                           15919 non-null  object
 37  Consumption                    14013 non-null  object
 38  CO2 Emission                   14111 non-null  object
 39  Emission Class                 12898 non-null  object
 40
Comfort & Convenience
        14999 non-null  object
 41
Entertainment & Media
        14545 non-null  object
 42
Extras
                       12957 non-null  object
 43
Safety & Security
            14937 non-null  object
 44  description                    15919 non-null  object
 45  Emission Label                 3985 non-null   object
 46  Gears                          11207 non-null  object
 47  Country version                7586 non-null   object
 48  Electricity consumption        137 non-null    object
 49  Last Service Date              566 non-null    object
 50  Other Fuel Types               880 non-null    object
 51  Availability                   635 non-null    object
 52  Last Timing Belt Service Date  16 non-null     object
 53  Available from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [751]:
df.duplicated

<bound method DataFrame.duplicated of                                                      url      make_model  \
0      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1
1      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1
2      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1
3      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1
4      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1
...                                                  ...             ...
15914  https://www.autoscout24.com//offers/renault-es...  Renault Espace
15915  https://www.autoscout24.com//offers/renault-es...  Renault Espace
15916  https://www.autoscout24.com//offers/renault-es...  Renault Espace
15917  https://www.autoscout24.com//offers/renault-es...  Renault Espace
15918  https://www.autoscout24.com//offers/renault-es...  Renault Espace

                                       short_description body_type  price  \
0            Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770
1                                         1.8 TFSI sport    Sedans  14500
2      Sportback 1.6 TDI S tronic Einparkhilfe plus+m...    Sedans  14640
3                                1.4 TDi Design S tronic    Sedans  14500
4      Sportback 1.4 TDI S-Tronic S-Line Ext. admired...    Sedans  16790
...                                                  ...       ...    ...
15914              Blue dCi 200CV EDC Executive 4Control       Van  39950
15915                TCe 225 EDC GPF LIM Deluxe Pano,RFK       Van  39885
15916  Blue dCi 200 EDC Initiale Paris Leder LED Navi...       Van  39875
15917  Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...       Van  39700
15918        INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX       Van  40999

                    vat         km registration         prev_owner  kW  ...  \
0        VAT deductible  56,013 km      01/2016  2 previous owners NaN  ...
1      Price negotiable  80,000 km      03/2017               None NaN  ...
2        VAT deductible  83,450 km      02/2016   1 previous owner NaN  ...
3                  None  73,000 km      08/2016   1 previous owner NaN  ...
4                  None  16,200 km      05/2016   1 previous owner NaN  ...
...                 ...        ...          ...                ...  ..  ...
15914    VAT deductible       - km          -/-               None NaN  ...
15915    VAT deductible   9,900 km      01/2019   1 previous owner NaN  ...
15916    VAT deductible      15 km      03/2019   1 previous owner NaN  ...
15917    VAT deductible      10 km      06/2019               None NaN  ...
15918    VAT deductible       - km      01/2019   1 previous owner NaN  ...

                                             description   Emission Label  \
0      [\n, Sicherheit:,  , Deaktivierung f√ºr Beifahr...              NaN
1      [\nLangstreckenfahrzeug daher die hohe Kilomet...  [\n4 (Green)\n]
2      [\n, Fahrzeug-Nummer: AM-95365,  , Ehem. UPE 2...  [\n4 (Green)\n]
3      [\nAudi A1: , - 1e eigenaar , - Perfecte staat...              NaN
4      [\n, Technik & Sicherheit:, Xenon plus, Klimaa...              NaN
...                                                  ...              ...
15914  [\nVettura visionabile nella sede in Via Roma ...              NaN
15915  [\nDach: Panorama-Glas-Schiebedach, Lackierung...              NaN
15916  [\n, Getriebe:,  Automatik, Technik:,  Bordcom...              NaN
15917  [\nDEK:[2691331], Renault Espace Blue dCi 200C...              NaN
15918  [\n, Sicherheit Airbags:,  , Seitenairbag,  , ...  [\n4 (Green)\n]

         Gears Country version Electricity consumption Last Service Date  \
0          NaN             NaN                     NaN               NaN
1      [\n7\n]             NaN                     NaN               NaN
2          NaN             NaN                     NaN               NaN
3      [\n6\n]             NaN                     NaN               NaN
4          NaN   [\nGermany\n]                     NaN               NaN
...        ...             ...                     ...               ...
15914  [\n6\n]             NaN                     NaN               NaN
15915  [\n7\n]   [\nGermany\n]                     NaN               NaN
15916  [\n6\n]   [\nAustria\n]                     NaN               NaN
15917  [\n6\n]             NaN                     NaN               NaN
15918      NaN   [\nGermany\n]                     NaN               NaN

      Other Fuel Types                   Availability  \
0                  NaN                            NaN
1                  NaN                            NaN
2                  NaN                            NaN
3                  NaN                            NaN
4                  NaN                            NaN
...                ...                            ...
15914              NaN                            NaN
15915     [[], [], []]    \nin 5 days from ordering\n
15916              NaN  \nin 120 days from ordering\n
15917              NaN                            NaN
15918              NaN                            NaN

      Last Timing Belt Service Date Available from
0                               NaN            NaN
1                               NaN            NaN
2                               NaN            NaN
3                               NaN            NaN
4                               NaN            NaN
...                             ...            ...
15914                           NaN            NaN
15915                           NaN            NaN
15916                           NaN            NaN
15917                           NaN            NaN
15918                           NaN            NaN

[15919 rows x 54 columns]>

In [752]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'Type',
       'Previous Owners', 'Next Inspection', 'Inspection new', 'Warranty',
       'Full Service', 'Non-smoking Vehicle', 'null', 'Make', 'Model',
       'Offer Number', 'First Registration', 'Body Color', 'Paint Type',
       'Body Color Original', 'Upholstery', 'Body', 'Nr. of Doors',
       'Nr. of Seats', 'Model Code', 'Gearing Type', 'Displacement',
       'Cylinders', 'Weight', 'Drive chain', 'Fuel', 'Consumption',
       'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n',
       '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n',
       'description', 'Emission Label', 'Gears', 'Country version',
       'Electricity consumption', 'Last Service Date', 'Other Fuel Types',
       'Availability', 'Last Timing Belt Service Date', 'Available from'],
      dtype='object')

In [753]:
!pip install skimpy
from skimpy import clean_columns
# columns = df.columns
# messy_df = pd.DataFrame(data = [], columns = columns, index = [0])
# print(messy_df)
# clean_df = clean_columns(messy_df)
# clean_df.columns.tolist()

Requirement already satisfied: skimpy in c:\users\elitebook\anaconda3\lib\site-packages (0.0.6)
Requirement already satisfied: click<9.0.0,>=8.1.3 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (8.1.3)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (1.0.0)
Requirement already satisfied: black<23.0.0,>=22.3.0 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (22.6.0)
Requirement already satisfied: Pygments<3.0.0,>=2.10.0 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (2.10.0)
Requirement already satisfied: pandas<2.0.0,>=1.3.2 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (1.3.4)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (1.23.1)
Requirement already satisfied: ipykernel<7.0.0,>=6.7.0 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (6.15.1)
Requirement already satisfied: typeguard<3.0.0,>=2.12.1 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (2.13.3)
Requirement already satisfied: rich<13.0,>=10.9 in c:\users\elitebook\anaconda3\lib\site-packages (from skimpy) (12.5.1)
Requirement already satisfied: platformdirs>=2 in c:\users\elitebook\anaconda3\lib\site-packages (from black<23.0.0,>=22.3.0->skimpy) (2.5.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\elitebook\anaconda3\lib\site-packages (from black<23.0.0,>=22.3.0->skimpy) (3.10.0.2)
Requirement already satisfied: tomli>=1.1.0 in c:\users\elitebook\anaconda3\lib\site-packages (from black<23.0.0,>=22.3.0->skimpy) (2.0.1)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\elitebook\anaconda3\lib\site-packages (from black<23.0.0,>=22.3.0->skimpy) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\elitebook\anaconda3\lib\site-packages (from black<23.0.0,>=22.3.0->skimpy) (0.4.3)
Requirement already satisfied: colorama in c:\users\elitebook\anaconda3\lib\site-packages (from click<9.0.0,>=8.1.3->skimpy) (0.4.4)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.1.2)
Requirement already satisfied: nest-asyncio in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.5.1)
Requirement already satisfied: tornado>=6.1 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (6.1)
Requirement already satisfied: traitlets>=5.1.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.1.0)
Requirement already satisfied: packaging in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (21.0)
Requirement already satisfied: psutil in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.8.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (6.1.12)
Requirement already satisfied: ipython>=7.23.1 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (7.29.0)
Requirement already satisfied: debugpy>=1.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.4.1)
Requirement already satisfied: pyzmq>=17 in c:\users\elitebook\anaconda3\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (22.2.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\elitebook\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (58.0.4)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (3.0.20)
Requirement already satisfied: pickleshare in c:\users\elitebook\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.7.5)
Requirement already satisfied: backcall in c:\users\elitebook\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.0)
Requirement already satisfied: decorator in c:\users\elitebook\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (5.1.0)
Requirement already satisfied: jedi>=0.16 in c:\users\elitebook\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\elitebook\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.8.2)
Requirement already satisfied: jupyter-console in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.4.0)
Requirement already satisfied: qtconsole in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (5.1.1)
Requirement already satisfied: nbconvert in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.1.0)
Requirement already satisfied: ipywidgets in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (7.6.5)
Requirement already satisfied: notebook in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.4.5)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.7.0->skimpy) (4.8.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.7.0->skimpy) (2.8.2)
Requirement already satisfied: pywin32>=1.0 in c:\users\elitebook\anaconda3\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.7.0->skimpy) (228)
Requirement already satisfied: pytz>=2017.3 in c:\users\elitebook\anaconda3\lib\site-packages (from pandas<2.0.0,>=1.3.2->skimpy) (2021.3)
Requirement already satisfied: wcwidth in c:\users\elitebook\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\users\elitebook\anaconda3\lib\site-packages (from python-dateutil>=2.1->jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.7.0->skimpy) (1.16.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\elitebook\anaconda3\lib\site-packages (from rich<13.0,>=10.9->skimpy) (0.9.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (5.1.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (1.0.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\elitebook\anaconda3\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (3.5.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\elitebook\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\elitebook\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\elitebook\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (21.2.0)
Requirement already satisfied: prometheus-client in c:\users\elitebook\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.11.0)
Requirement already satisfied: jinja2 in c:\users\elitebook\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.11.3)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\elitebook\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\elitebook\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.9.4)
Requirement already satisfied: argon2-cffi in c:\users\elitebook\anaconda3\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (20.1.0)
Requirement already satisfied: pywinpty>=0.5 in c:\users\elitebook\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\elitebook\anaconda3\lib\site-packages (from argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.14.6)
Requirement already satisfied: pycparser in c:\users\elitebook\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\elitebook\anaconda3\lib\site-packages (from jinja2->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.1.1)
Requirement already satisfied: testpath in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (1.4.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.8.4)
Requirement already satisfied: defusedxml in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.7.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.5.3)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.3)
Requirement already satisfied: bleach in c:\users\elitebook\anaconda3\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (4.0.0)
Requirement already satisfied: async-generator in c:\users\elitebook\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (1.10)
Requirement already satisfied: webencodings in c:\users\elitebook\anaconda3\lib\site-packages (from bleach->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\elitebook\anaconda3\lib\site-packages (from packaging->ipykernel<7.0.0,>=6.7.0->skimpy) (3.0.4)
Requirement already satisfied: qtpy in c:\users\elitebook\anaconda3\lib\site-packages (from qtconsole->jupyter<2.0.0,>=1.0.0->skimpy) (1.10.0)

In [754]:
df = clean_columns(df)
# cleaning column names using skimpy clean_columns method

42 column names have been cleaned

In [755]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'k_w', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'non_smoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co_2_emission', 'emission_class', 'comfort_&_convenience',
       'entertainment_&_media', 'extras', 'safety_&_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [756]:
df.rename(columns = {'k_w':'kW',
                     'co_2_emission':'co2_emission',
                     'comfort_&_convenience': 'comfort&convenience',
                    'entertainment_&_media':'entertainment&media',
                    'safety_&_security':'safety_&_security'}, inplace = True)

In [757]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'non_smoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'comfort&convenience',
       'entertainment&media', 'extras', 'safety_&_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [758]:
df.make_model.value_counts()

Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64

In [759]:
df.isnull().sum()/len(df)*100 # percentages of null values in each column

url                                0.000000
make_model                         0.000000
short_description                  0.288963
body_type                          0.376908
price                              0.000000
vat                               28.349771
km                                 0.000000
registration                       0.000000
prev_owner                        42.892141
kW                               100.000000
hp                                 0.000000
type                               0.012564
previous_owners                   41.711163
next_inspection                   77.793831
inspection_new                    75.299956
warranty                          34.047365
full_service                      48.395000
non_smoking_vehicle               54.915510
null                               0.000000
make                               0.000000
model                              0.000000
offer_number                      19.944720
first_registration                10.032037
body_color                         3.750236
paint_type                        36.258559
body_color_original               23.613292
upholstery                        23.368302
body                               0.376908
nr_of_doors                        1.331742
nr_of_seats                        6.137320
model_code                        68.729192
gearing_type                       0.000000
displacement                       3.115774
cylinders                         35.680633
weight                            43.809285
drive_chain                       43.080596
fuel                               0.000000
consumption                       11.973114
co2_emission                      11.357497
emission_class                    18.977323
comfort&convenience                5.779257
entertainment&media                8.631195
extras                            18.606696
safety_&_security                  6.168729
description                        0.000000
emission_label                    74.967021
gears                             29.599849
country_version                   52.346253
electricity_consumption           99.139393
last_service_date                 96.444500
other_fuel_types                  94.472015
availability                      96.011056
last_timing_belt_service_date     99.899491
available_from                    98.291350
dtype: float64

In [760]:
import re
def get_diff_category_column(Series:pd.Series, exclude=''',/\n''', pattern=r'''[,\n]| /''', strip='''\n' "!?|.,*+-_/][\\n''', diff_value=list()):  
    diff_value.clear()
    column = Series.dropna().apply(str).str.strip(strip)
    for row in column:
        if not any(x in exclude for x in row) and row not in diff_value:
            diff_value.append(row)
        else:
            for data in map(lambda x: x.strip(strip), filter(None, re.split(pattern, row))):
                if data not in diff_value:
                    diff_value.append(data)
    return dict(enumerate(sorted(diff_value)))

In [761]:
get_diff_category_column(df["comfort&convenience"])

{0: 'Air conditioning',
 1: 'Air suspensio',
 2: 'Armrest',
 3: 'Automatic climate control',
 4: 'Auxiliary heating',
 5: 'Cruise control',
 6: 'Electric Starter',
 7: 'Electric tailgate',
 8: 'Electrical side mirrors',
 9: 'Electrically adjustable seats',
 10: 'Electrically heated windshield',
 11: 'Heads-up display',
 12: 'Heated steering wheel',
 13: 'Hill Holder',
 14: 'Keyless central door lock',
 15: 'Leather seats',
 16: 'Leather steering wheel',
 17: 'Light sensor',
 18: 'Lumbar support',
 19: 'Massage seats',
 20: 'Multi-function steering wheel',
 21: 'Navigation system',
 22: 'Panorama roof',
 23: 'Park Distance Control',
 24: 'Parking assist system camera',
 25: 'Parking assist system self-steering',
 26: 'Parking assist system sensors front',
 27: 'Parking assist system sensors rear',
 28: 'Power windows',
 29: 'Rain sensor',
 30: 'Seat heating',
 31: 'Seat ventilatio',
 32: 'Split rear seats',
 33: 'Start-stop system',
 34: 'Sunroof',
 35: 'Tinted windows',
 36: 'Wind deflector',
 37: 'Windshield'}

In [762]:
def check_df(col):
    print('column name : ', col)
    print('-+-+-'*30)
    print('Per_of_Nulls   : ', '%', round(df[col].isnull().sum() / df.shape[0]*100, 2))
    print('Num_of_Nulls   : ', df[col].isnull().sum())
    print(df[col].value_counts(dropna = False))
    print("*"*30)
    print("\n\n")

In [763]:
for col in df.columns :
    check_df(col)

column name :  url
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e                  1
https://www.autoscout24.com//offers/opel-insignia-bus-inno-2-0-cdti-aut-navi-bi-xe-led-e6-diesel-black-8710b253-dd98-4ed0-9d46-cbad2d79532b                1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-10b7463b-9f56-4348-af35-df3432b2b585    1
https://www.autoscout24.com//offers/opel-insignia-2-0cdti-st-business-innovation-navi-bt-diesel-black-ba5a3368-dedc-4e51-9127-3976b26e93c2                 1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-7b52f054-78d3-4d5e-9370-8a7d081d7edd    1
                                                                                                                                                          ..
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-black-cf50f7b1-4d7b-466f-93a2-4e11ec0b4107                        1
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-grey-3f47eb34-15c4-4763-860d-78fcbbd2c9ff                         1
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-silver-f7a4bc95-b2ef-4bac-9497-6bcbcd05db0b                       1
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-silver-1c94c7a2-67b5-49ca-ae42-42a6800fb3f5                       1
https://www.autoscout24.com//offers/renault-espace-initiale-paris-tce-225-edc-gpf-navi-shz-aux-gasoline-grey-0bd690d9-7e93-4cab-bc5a-9d5b63402481          1
Name: url, Length: 15919, dtype: int64
******************************



column name :  make_model
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64
******************************



column name :  short_description
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.29
Num_of_Nulls   :  46
SPB 1.6 TDI 116 CV S tronic Sport                 64
NaN                                               46
1.4 66kW (90CV) Selective                         40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH             38
SPB 30 TDI S tronic Business                      35
                                                  ..
K Sports Tourer Business **Navi*Voll**             1
1.0 Turbo ecoFLEX Automatic Elective Park Navi     1
1.6 CDTI Business *Navi*Automatik*Spurh.*          1
1.6 136 CV Automatica Navi E 6 Garanzia Full       1
TCe 225 EDC GPF LIM Deluxe Pano,RFK                1
Name: short_description, Length: 10002, dtype: int64
******************************



column name :  body_type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64
******************************



column name :  price
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
14990    154
15990    151
10990    139
15900    106
17990    102
        ...
17559      1
17560      1
17570      1
17575      1
39875      1
Name: price, Length: 2956, dtype: int64
******************************



column name :  vat
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 28.35
Num_of_Nulls   :  4513
VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64
******************************



column name :  km
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ...
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64
******************************



column name :  registration
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64
******************************



column name :  prev_owner
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 42.89
Num_of_Nulls   :  6828
1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64
******************************



column name :  kW
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 100.0
Num_of_Nulls   :  15919
NaN    15919
Name: kW, dtype: int64
******************************



column name :  hp
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ...
84 kW        1
195 kW       1
44 kW        1
239 kW       1
9 kW         1
Name: hp, Length: 81, dtype: int64
******************************



column name :  type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.01
Num_of_Nulls   :  2
[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: type, Length: 170, dtype: int64
******************************



column name :  previous_owners
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 41.71
Num_of_Nulls   :  6640
\n1\n                                                                                        8101
NaN                                                                                          6640
\n2\n                                                                                         766
\n0\n                                                                                         163
\n3\n                                                                                          17
                                                                                             ...
[\n1\n, \n111 g CO2/km (comb)\n]                                                                1
[\n1\n, \nEuro 6\n]                                                                             1
[\n2\n, \n119 g CO2/km (comb)\n]                                                                1
[\n1\n, \n, 6.6 l/100 km (comb), \n, 8.1 l/100 km (city), \n, 5.7 l/100 km (country), \n]       1
[\n2\n, \n137 g CO2/km (comb)\n]                                                                1
Name: previous_owners, Length: 103, dtype: int64
******************************



column name :  next_inspection
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 77.79
Num_of_Nulls   :  12384

NaN                                       12384
\n04/2022\n                                  62
\n03/2021\n                                  38
\n03/2022\n                                  36
\n06/2021\n                                  34
                                          ...
[\n12/2018\n, \n97 g CO2/km (comb)\n]         1
[\n03/2022\n, \n1 (No sticker)\n]             1
[\n05/2021\n, \n93 g CO2/km (comb)\n]         1
[\n06/2021\n, \n93 g CO2/km (comb)\n]         1
[\n01/2022\n, \n168 g CO2/km (comb)\n]        1
Name: next_inspection, Length: 1400, dtype: int64
******************************



column name :  inspection_new
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 75.3
Num_of_Nulls   :  11987
NaN                                                                                            11987
[\nYes\n, \nEuro 6\n]                                                                            523
\nYes\n                                                                                          362
[\nYes\n, \n102 g CO2/km (comb)\n]                                                               174
[\nYes\n, \n4 (Green)\n]                                                                         166
                                                                                               ...
[\nYes\n, \n, 6 l/100 km (comb), \n, 8 l/100 km (city), \n, 4.9 l/100 km (country), \n]            1
[\nYes\n, \n, 6.8 l/100 km (comb), \n, 8.5 l/100 km (city), \n, 6.1 l/100 km (country), \n]        1
[\nYes\n, \n, 4.1 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 5.2 l/100 km (country), \n]        1
[\nYes\n, \n, 5.2 l/100 km (comb), \n, 6.8 l/100 km (city), \n, 4.3 l/100 km (country), \n]        1
[\nYes\n, \n172 g CO2/km (comb)\n]                                                                 1
Name: inspection_new, Length: 203, dtype: int64
******************************



column name :  warranty
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 34.05
Num_of_Nulls   :  5420
NaN                                                                                                5420
[\n, \n, \nEuro 6\n]                                                                               1868
\n12 months\n                                                                                      1177
\n                                                                                                  979
\n24 months\n                                                                                       566
                                                                                                   ...
[\n72 months\n, \n125 g CO2/km (comb)\n]                                                              1
[\n60 months\n, \n14 g CO2/km (comb)\n]                                                               1
[\n24 months\n, \n121 g CO2/km (comb)\n]                                                              1
[\n12 months\n, \nEuro 6d\n]                                                                          1
[\n36 months\n, \n, 7.4 l/100 km (comb), \n, 9.6 l/100 km (city), \n, 6 l/100 km (country), \n]       1
Name: warranty, Length: 516, dtype: int64
******************************



column name :  full_service
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 48.39
Num_of_Nulls   :  7704
NaN                                                                                           7704
[\n, \n, \n4 (Green)\n]                                                                       2235
[\n, \n, \nEuro 6\n]                                                                          2097
[\n, \n]                                                                                      1702
[\n, \n, \nEuro 6d-TEMP\n]                                                                     399
                                                                                              ...
[\n, \n, \n80 g CO2/km (comb)\n]                                                                 1
[\n, \n, \n84 g CO2/km (comb)\n]                                                                 1
[\n, \n, \n, 6 l/100 km (comb), \n, 8 l/100 km (city), \n, 4.9 l/100 km (country), \n]           1
[\n, \n, \n, 4.9 l/100 km (comb), \n, 6.2 l/100 km (city), \n, 4.1 l/100 km (country), \n]       1
[\n, \n, \nEuro 4\n]                                                                             1
Name: full_service, Length: 123, dtype: int64
******************************



column name :  non_smoking_vehicle
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 54.92
Num_of_Nulls   :  8742
NaN                                                                                           8742
[\n, \n]                                                                                      3647
[\n, \n, \n4 (Green)\n]                                                                       1240
[\n, \n, \nEuro 6\n]                                                                          1127
[\n, \n, \nEuro 6d-TEMP\n]                                                                     345
                                                                                              ...
[\n, \n, \n, 5.6 l/100 km (comb), \n, 7.3 l/100 km (city), \n, 4.7 l/100 km (country), \n]       1
[\n, \n, \n122 g CO2/km (comb)\n]                                                                1
[\n, \n, \n158 g CO2/km (comb)\n]                                                                1
[\n, \n, \n150 g CO2/km (comb)\n]                                                                1
[\n, \n, \n175 g CO2/km (comb)\n]                                                                1
Name: non_smoking_vehicle, Length: 95, dtype: int64
******************************



column name :  null
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[]    15919
Name: null, dtype: int64
******************************



column name :  make
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
\nOpel\n       7343
\nAudi\n       5712
\nRenault\n    2864
Name: make, dtype: int64
******************************



column name :  model
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: model, dtype: int64
******************************



column name :  offer_number
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 19.94
Num_of_Nulls   :  3175
NaN                                               3175
[\nLT67679\n]                                       27
[\nUN89904\n]                                       27
[\nXJ38068\n]                                       27
[\nJV03654\n]                                       27
                                                  ...
[\n160_dcbb6c3e-a6da-43a3-8754-ccd994cec93b\n]       1
[\n6701576\n]                                        1
[\n6701569\n]                                        1
[\n158121\n]                                         1
[\nRe_30000008029\n]                                 1
Name: offer_number, Length: 11441, dtype: int64
******************************



column name :  first_registration
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 10.03
Num_of_Nulls   :  1597
[\n, 2018, \n]    4522
[\n, 2016, \n]    3674
[\n, 2017, \n]    3273
[\n, 2019, \n]    2853
NaN               1597
Name: first_registration, dtype: int64
******************************



column name :  body_color
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 3.75
Num_of_Nulls   :  597
[\n, Black, \n]     3745
[\n, Grey, \n]      3505
[\n, White, \n]     3406
[\n, Silver, \n]    1647
[\n, Blue, \n]      1431
[\n, Red, \n]        957
NaN                  597
[\n, Brown, \n]      289
[\n, Green, \n]      154
[\n, Beige, \n]      108
[\n, Yellow, \n]      51
[\n, Violet, \n]      18
[\n, Bronze, \n]       6
[\n, Orange, \n]       3
[\n, Gold, \n]         2
Name: body_color, dtype: int64
******************************



column name :  paint_type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 36.26
Num_of_Nulls   :  5772
[\nMetallic\n]       9794
NaN                  5772
[\nUni/basic\n]       347
[\nPerl effect\n]       6
Name: paint_type, dtype: int64
******************************



column name :  body_color_original
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 23.61
Num_of_Nulls   :  3759

NaN                                    3759
[\nOnyx Schwarz\n]                      338
[\nBianco\n]                            282
[\nMythosschwarz Metallic\n]            238
[\nBrillantschwarz\n]                   216
                                       ...
[\nRouge-Braun (G0Y)\n]                   1
[\nVARI COLRI DISPONIBILI\n]              1
[\nKokosnussbraun Metallic\n]             1
[\nFarbe frei w√§hlbar\n]                  1
[\nPerlmutt-Wei√ü Metallic (Wei√ü)\n]       1
Name: body_color_original, Length: 1928, dtype: int64
******************************



column name :  upholstery
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 23.37
Num_of_Nulls   :  3720
[\nCloth, Black\n]           5821
NaN                          3720
[\nPart leather, Black\n]    1121
[\nCloth\n]                  1005
[\nCloth, Grey\n]             891
[\nCloth, Other\n]            639
[\nFull leather, Black\n]     575
[\nBlack\n]                   491
[\nGrey\n]                    273
[\nOther, Other\n]            182
[\nPart leather\n]            140
[\nFull leather\n]            139
[\nFull leather, Brown\n]     116
[\nPart leather, Grey\n]      116
[\nOther, Black\n]            110
[\nFull leather, Other\n]      72
[\nFull leather, Grey\n]       67
[\nPart leather, Other\n]      65
[\nOther\n]                    56
[\nPart leather, Brown\n]      50
[\nalcantara, Black\n]         47
[\nVelour, Black\n]            36
[\nFull leather, Beige\n]      36
[\nCloth, Brown\n]             28
[\nVelour\n]                   16
[\nOther, Grey\n]              15
[\nCloth, Beige\n]             13
[\nBrown\n]                    12
[\nCloth, Blue\n]              12
[\nVelour, Grey\n]              8
[\nCloth, White\n]              8
[\nalcantara, Grey\n]           6
[\nCloth, Red\n]                5
[\nOther, Yellow\n]             4
[\nPart leather, Red\n]         3
[\nBeige\n]                     3
[\nPart leather, White\n]       2
[\nFull leather, Blue\n]        2
[\nalcantara, Other\n]          2
[\nalcantara\n]                 2
[\nWhite\n]                     2
[\nPart leather, Beige\n]       2
[\nBlue\n]                      2
[\nCloth, Orange\n]             1
[\nFull leather, Red\n]         1
[\nOther, Brown\n]              1
[\nFull leather, White\n]       1
Name: upholstery, dtype: int64
******************************



column name :  body
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
[\n, Sedans, \n]           7903
[\n, Station wagon, \n]    3553
[\n, Compact, \n]          3153
[\n, Van, \n]               783
[\n, Other, \n]             290
[\n, Transporter, \n]        88
NaN                          60
[\n, Off-Road, \n]           56
[\n, Coupe, \n]              25
[\n, Convertible, \n]         8
Name: body, dtype: int64
******************************



column name :  nr_of_doors
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 1.33
Num_of_Nulls   :  212
[\n5\n]    11575
[\n4\n]     3079
[\n3\n]      832
[\n2\n]      219
NaN          212
[\n1\n]        1
[\n7\n]        1
Name: nr_of_doors, dtype: int64
******************************



column name :  nr_of_seats
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 6.14
Num_of_Nulls   :  977
[\n5\n]    13336
[\n4\n]     1125
NaN          977
[\n7\n]      362
[\n2\n]      116
[\n6\n]        2
[\n3\n]        1
Name: nr_of_seats, dtype: int64
******************************



column name :  model_code
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 68.73
Num_of_Nulls   :  10941
NaN               10941
[\n0035/BCB\n]      268
[\n0588/BNO\n]      245
[\n0588/BDB\n]      206
[\n0588/BHX\n]      188
                  ...
[\n0035/AVN\n]        1
[\n0035/BEM\n]        1
[\n0035/BAG\n]        1
[\n0035/BAA\n]        1
[\n3333/BKG\n]        1
Name: model_code, Length: 233, dtype: int64
******************************



column name :  gearing_type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[\n, Manual, \n]            8153
[\n, Automatic, \n]         7297
[\n, Semi-automatic, \n]     469
Name: gearing_type, dtype: int64
******************************



column name :  displacement
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 3.12
Num_of_Nulls   :  496
[\n1,598 cc\n]    4761
[\n999 cc\n]      2438
[\n1,398 cc\n]    1314
[\n1,399 cc\n]     749
[\n1,229 cc\n]     677
                  ...
[\n122 cc\n]         1
[\n1,198 cc\n]       1
[\n1,195 cc\n]       1
[\n2,967 cc\n]       1
[\n1,800 cc\n]       1
Name: displacement, Length: 78, dtype: int64
******************************



column name :  cylinders
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 35.68
Num_of_Nulls   :  5680
[\n4\n]    8105
NaN        5680
[\n3\n]    2104
[\n5\n]      22
[\n6\n]       3
[\n8\n]       2
[\n2\n]       2
[\n1\n]       1
Name: cylinders, dtype: int64
******************************



column name :  weight
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 43.81
Num_of_Nulls   :  6974
NaN               6974
[\n1,163 kg\n]     574
[\n1,360 kg\n]     356
[\n1,165 kg\n]     301
[\n1,335 kg\n]     242
                  ...
[\n1,960 kg\n]       1
[\n1,258 kg\n]       1
[\n1,167 kg\n]       1
[\n1,331 kg\n]       1
[\n2,037 kg\n]       1
Name: weight, Length: 435, dtype: int64
******************************



column name :  drive_chain
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 43.08
Num_of_Nulls   :  6858
[\nfront\n]    8886
NaN            6858
[\n4WD\n]       171
[\nrear\n]        4
Name: drive_chain, dtype: int64
******************************



column name :  fuel
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
                                                                                                                       ...
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91, \n]                                                          1
[\n, Super Plus 98 / Super E10 95, \n]                                                                                    1
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98, \n]       1
[\n, Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98, \n]       1
[\n, Super Plus 98 / Super 95 / Super Plus E10 98, \n]                                                                    1
Name: fuel, Length: 77, dtype: int64
******************************



column name :  consumption
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 11.97
Num_of_Nulls   :  1906
NaN                                                                                   1906
[[3.9 l/100 km (comb)], [4.1 l/100 km (city)], [3.7 l/100 km (country)]]               304
[[4.2 l/100 km (comb)], [5 l/100 km (city)], [3.7 l/100 km (country)]]                 276
[[5.4 l/100 km (comb)], [6.8 l/100 km (city)], [4.5 l/100 km (country)]]               257
[[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]               253
                                                                                      ...
[[4.2 l/100 km (comb)], [5.3 l/100 km (city)], [3.6 l/100 km (country)]]                 1
[\n, 5.1 l/100 km (comb), \n, 6.4 l/100 km (city), \n, 4.3 l/100 km (country), \n]       1
[[4.6 l/100 km (comb)], [5.4 l/100 km (city)], [6.7 l/100 km (country)]]                 1
[\n, 6.3 l/100 km (comb), \n, \n, \n]                                                    1
[\n, 7.4 l/100 km (comb), \n, 9.6 l/100 km (city), \n, 6 l/100 km (country), \n]         1
Name: consumption, Length: 882, dtype: int64
******************************



column name :  co2_emission
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 11.36
Num_of_Nulls   :  1808
NaN                            1808
[\n120 g CO2/km (comb)\n]       740
[[], [], []]                    628
[\n99 g CO2/km (comb)\n]        545
[\n97 g CO2/km (comb)\n]        537
                               ...
[\n14 g CO2/km (comb)\n]          1
[\n1,060 g CO2/km (comb)\n]       1
[\n51 g CO2/km (comb)\n]          1
[\n165 g CO2/km (comb)\n]         1
[\n193 g CO2/km (comb)\n]         1
Name: co2_emission, Length: 124, dtype: int64
******************************



column name :  emission_class
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 18.98
Num_of_Nulls   :  3021
[\nEuro 6\n]          10139
NaN                    3021
[\nEuro 6d-TEMP\n]     1845
[[], [], []]            607
[\nEuro 6c\n]           127
[\nEuro 5\n]             78
[\nEuro 6d\n]            62
[\nEuro 4\n]             40
Name: emission_class, dtype: int64
******************************



column name :  comfort&convenience
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 5.78
Num_of_Nulls   :  920

NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          920
[Air conditioning, Electrical side mirrors, Hill Holder, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                      216
[Air conditioning, Electrical side mirrors, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                                   134
[Air conditioning, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            130
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                                                                                                                                         105
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
[Air conditioning, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Split rear seats, Start-stop system, Tinted windows]                                                                                                                                                                                                                   1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system camera, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof]                                                                                                   1
[Air conditioning, Armrest, Cruise control, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Park Distance Control, Parking assist system camera, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows]                                                                                                                     1
[Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Light sensor, Multi-function steering wheel, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating]                                                                                                                                                                                                                          1
[Air conditioning, Automatic climate control, Cruise control, Electrically heated windshield, Electrical side mirrors, Electric tailgate, Heads-up display, Heated steering wheel, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Navigation system, Park Distance Control, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof]      1
Name: comfort&convenience, Length: 6199, dtype: int64
******************************



column name :  entertainment&media
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 8.63
Num_of_Nulls   :  1374
NaN                                                                                                           1374
[Bluetooth, Hands-free equipment, On-board computer, Radio, USB]                                              1282
[Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB]                                          982
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]                               783
[On-board computer, Radio]                                                                                     487
                                                                                                              ...
[Bluetooth, CD player, Digital radio, Hands-free equipment, Radio]                                               1
[CD player, Hands-free equipment, MP3, Radio, USB]                                                               1
[MP3, Radio, Sound system, USB]                                                                                  1
[Bluetooth, MP3, On-board computer, Radio, Television, USB]                                                      1
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, Sound system, Television, USB]       1
Name: entertainment&media, Length: 347, dtype: int64
******************************



column name :  extras
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 18.61
Num_of_Nulls   :  2962
[Alloy wheels]                                                                                                     3245
NaN                                                                                                                2962
[Alloy wheels, Touch screen]                                                                                        697
[Alloy wheels, Voice Control]                                                                                       577
[Alloy wheels, Touch screen, Voice Control]                                                                         541
                                                                                                                   ...
[Alloy wheels, Catalytic Converter, Shift paddles, Sport package, Sport seats, Sport suspension, Voice Control]       1
[Alloy wheels, Catalytic Converter, Roof rack, Sport package, Sport seats, Trailer hitch]                             1
[Alloy wheels, Catalytic Converter, Ski bag, Sport package, Voice Control]                                            1
[Catalytic Converter, Roof rack, Sport seats, Sport suspension]                                                       1
[Alloy wheels, Shift paddles, Ski bag, Sport seats, Sport suspension, Touch screen, Voice Control]                    1
Name: extras, Length: 660, dtype: int64
******************************



column name :  safety_&_security
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 6.17
Num_of_Nulls   :  982

NaN                                                                                                                                                                                                                                                                                                                                                                                  982
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                                                           538
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                                                                       480
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]                                                                                                                                     275
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                               272
                                                                                                                                                                                                                                                                                                                                                                                    ...
[ABS, Central door lock, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag]                                                                                                                                                                                                                                                        1
[ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Emergency brake assistant, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                     1
[ABS, Adaptive Cruise Control, Alarm system, Central door lock, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Lane departure warning system, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]                                                 1
[ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Power steering, Tire pressure monitoring system, Traction control]                                                                                                                                                        1
[ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Emergency brake assistant, Fog lights, Immobilizer, Isofix, Lane departure warning system, LED Daytime Running Lights, LED Headlights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traffic sign recognition]      1
Name: safety_&_security, Length: 4444, dtype: int64
******************************



column name :  description
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        636
[\n, \n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   30
[\n, Fahrzeugbeschreibung,  Sichern Sie sich diesen Renault Clio 1.6 TCE Energy Sport Trophy zum Top-Preis inklusive dem , AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  1.Hand, deutsche Auslieferung, Unfallfrei, scheckheftgepflegt,  , Highlights,  , Audio-Navigationssystem R-Link Evolution mit Touchscreen und Carminat TomTom,  , Sportsitze ,  , Sportfahrwerk,  , Scheinwerfer Full-LED , Komfort,  , Geschwindigkeits-Regelanlage (Tempomat) ,  , Klimaanlage,  , Einparkhilfe hinten,  , Multifunktionslenkrad (Sport/Leder) mit Schaltwippen/-tasten ,  , Fensterheber elektr. mit Impulsgeber links/rechts vorn,  , Zentralverriegelung / Startanlage Handsfree Entry & Drive ,  , Berganfahr-Assistent (HSA) , Multimedia,  , Audiosystem: Radio R & GO (Bluetooth, DAB-Tuner),  , Bordcomputer,  , Freisprecheinrichtung Bluetooth ,  , USB-Anschluss inkl. AUX-IN-Anschluss (Plug & Music) , Licht und Sicht,  , Au√üenspiegel elektr. verstell- und heizbar ,  , Licht- und Regensensor ,  , Tagfahrlicht LED ,  , Nebelscheinwerfer LED ,  , Coming-Home-Lichtfunktion ,  , Heckleuchten LED , Sicherheit,  , Isofix-Aufnahmen f√ºr Kindersitz ,  , Seitenairbag vorn,  , Wegfahrsperre,  , Differentialsperre,  , Bremsassistent ,  , Elektron. Stabilit√§ts-Programm (ESP),  , Anti-Blockier-System (ABS),  , Anti-Submarining-Airbag im Fond,  , Airbag Fahrer-/Beifahrerseite ,  , Differentialsperre ,  , Reifendruck-Kontrollsystem ,  , Untersteuerungskontrolle (USC) ,  , Antischlupfregelung (ASR) , Weiteres,  , Start/Stop-Anlage ,  , Servolenkung geschwindigkeitsabh√§ngig,  , R.S. Drive (Fahrmodusschalter) ,  , Gep√§ckraumabdeckung / Rollo ,  , Heckdiffusor ,  , LM-Felgen ,  , Heckspoiler (Renault Sport) ,  , Pedale Aluminium ,  , Energier√ºckgewinnung (Energy Smart Management) , ...]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              27
[\nPosibilidad de prueba del veh√≠culo hasta 5 d√≠as. Consultar condiciones. PVP para particulares. Varias unidades y colores disponibles. Precios publicados para veh√≠culos industriales (furgonetas) v√°lidos para compradores aut√≥nomos o empresas, consultar condiciones para particulares. Las im√°genes y kil√≥metros pueden no corresponder con el modelo anunciado. Para confirmar p√≥ngase en contacto con nuestro departamento comercial. Consulta las excepcionales condiciones de financiaci√≥n que tenemos disponibles. Precio de venta final IVA y gastos de transferencia incluidos. Horario de atenci√≥n al cliente: Lunes a Viernes de 09:00 a 18:00.\n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          27
[\nSichern Sie sich diesen RENAULT CLIO 1.2 LIMITED zum Top-Preis inklusive dem, AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  2.Hand, mindestens 12 Monate g√ºltige HU und AU, deutsche Ausf√ºhrung, unfallfrei ,  , Highlights,  , Audio-Navigationssystem mit Touchscreen-Farbdisplay, Komfort,  , Klimaanlage ,  , Multifunktionslenkrad in Leder ,  , Berganfahr-Assistent (HSA),  , Fensterheber elektrisch vorn ,  , Geschwindigkeits-Regelanlage (Tempomat) ,  , Heckscheibe heizbar ,  , Sitz vorn links h√∂henverstellbar,  , Sitz vorn rechts umklappbar ,  , Stau-/Ablagefach im Laderaumboden ,  , Zentralverriegelung mit Fernbedienung , Multimedia,  , Radio R&GO,  , Bluetooth Freisprechanlage ,  , USB-/AUX-Schnittstelle ,  , Bordcomputer,  , Licht und Sicht,  , Tagfahrlicht LED ,  , Au√üenspiegel elektrisch verstell- und heizbar, Sicherheit,  , Airbag f√ºr Fahrer und Beifahrer,  , Beifahrerairbag deaktivierbar ,  , Seitenairbags vorn ,  , Kopfairbagsystem,  , Anti-Blockier-System (ABS),  , Elektronische Bremskraftverteilung ,  , Elektronische Stabilit√§ts-Programm (ESP) ,  , Reifen-Reparaturkit ,  , Reifendruck-Kontrollsystem ,  , Untersteuerungskontrolle (USC) ,  , ISOFIX Kindersitzverankerung , Weiteres,  , Dachreling silber ,  , Look-Paket Chrom (au√üen) ,  , Look-Paket Grau (innen) ,  , R&GO-Paket ,  , Style-Paket ,  Ihr , AUTOHERO-RUNDUM-SORGLOS-PAKET,  beinhaltet:, Kostenlose Lieferung in Ihre N√§he, Optische & technische Aufbereitung, Mindestens 12 Monate g√ºltige HU und AU, 1-Jahr-Premium-Garantie, Zulassung inklusive , 14-Tage-R√ºckgaberecht, Markenunabh√§ngige Inzahlungnahme , Individuelle Finanzierungen zu fairen Konditionen,  , HIER GEHT ES ZUR 360¬∞ - ANSICHT DES FAHRZEUGES:, :, https://www.autohero.com/de/renault-clio-1-2-limited/id/30f99516-8785-47e7-a4a3-6cdac4d8e633/,  , Haftungsausschluss, :, F√ºr Angaben vom Verk√§ufer, des Herstellers oder von Datenbankabfragen √ºbernimmt Autohero keine Haftung. √Ñnderungen, Zwischenverkauf und Irrt√ºmer sind vorbehalten.\n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                27

In [764]:
# bazƒ± s√ºtunlarda s√ºtun isimleri a√ßƒ±klanƒ±r halde birimi ile birlikte yazƒ±lacak
# url sonra bakƒ±lacak.
# make_model, make ve model s√ºtunlarƒ± incelenecek eksik veriler tamamlanacak ve make_model veya make ve model s√ºtunu kalacak.
# short_description sonra bakƒ±lacak
# body_type da bulunan none deƒüerler doldurulacak. Dolduramazsak other lara ekleyebiliriz
# price s√ºtunu floata √ßevrilecek (‚Ç¨ simgesi konacak)
# vat(value add tax) s√ºtununda null deƒüerler fazla (28%) bu s√ºtuna bakƒ±lacak ve ili≈ükili olduƒüunu d√º≈ü√ºnd√ºƒü√ºm√ºz kolonlar vastasƒ±yla doldurulacak
# km s√ºtununda ',' ve 'km' ler arƒ±ndƒ±rƒ±lacak. Ayrƒ±ca '-' deƒüerlerine bakƒ±lƒ±p ne anlama geldiƒüine bakƒ±lacak
# registration ve first registration aynƒ± deƒüerlendirilebilir ve buradan age s√ºtunu olu≈üturulabilir
# prew_owner √ßok fazla null deƒüer var. ara√ß ya≈üƒ±na g√∂re d√ºzenlenebilir 
# kw silinecek (Tamamƒ± none deƒüerler)
# hp s√ºtununda 'kw' ler silinecek (hp ye √ßevrilebilir). strange  deƒüerler var. '-' deƒüerleri var
# type s√ºtunu listeden √ßƒ±karaƒüƒ±z.fuel ile koordineli doldurma i≈ülemi yapƒ±lacak. Yakƒ±t ksƒ±ƒ±mlarƒ± silinecek. (pre-registration gibi deƒüerler var  deƒüeri new oalrak deƒüi≈ütirilecek)
# previous_owners '\n' lerden temizlenecek. s√ºtun ile ilgisi olmayan ≈üeyler var
# next_inspection temizlenecek. null deƒüer √ßok fazla.
# inspection_new √ßok fazla null deƒüer. diƒüer s√ºtunlarƒ± tamamlamaya √ßalƒ±≈üacaƒüƒ±z
# warranty √ßok fazla null ve bo≈ü deƒüer var month ƒ±n √∂√ºndeki sayƒ±larƒ± extract yapacaƒüƒ±z. inr veya floata √ßevireceƒüiz
# full servis s√ºtumu tekrar incelenecek ve √∂nem derecesine bakƒ±lƒ±p d√º≈ü√ºlecek
# non_smoking_vehicle d√º≈ü√ºlecek
# null s√ºtunu d√º≈ü√ºlecek
# offer_number bi anlamƒ± yok d√º≈ü√ºlecek
# body_color a g√∂re grƒ±uplama yapƒ±lacak fiyat analizi yapƒ±lacak sonra kategorize edilecek
# paint_type s√ºtunu temizlenecek cex kalacak (3 type var metalik non-metalik, perl)
# body_color ve body _color_original birlikte incelenip null deƒüerler doldurrulmaya √ßalƒ±≈üƒ±lacak sonra original silinecek
# upholstery s√ºtunu temizlenecek kategorize edilecek
# body s√ºtunu temizlenecek
# nr_of_doors s√ºtunun da strange value var 
# nr_of_seats temizlenecek null deƒüerler doldurulacak
# model_code tekrar bakƒ±lacak ve d√º≈ü√ºlecek
# gearing_type temizlenecek 
# displacement temizlenecek 'cc' ve ',' deƒüerleri silinecek. ismi 'engine_displacement' deƒüi≈üecek 
# cylinders temizlenecek null deƒüerler doldurmaya √ßalƒ±≈üƒ±lacak. engine displacement s√ºtunu ile birlikte deƒüerlendirilecek
# weight null deƒüerler var temizlenecek d√º≈ü√ºlebilir veya doldurulabilir veya kategorize edilebilir. 
# drive_chain temizlenecek ve doldurulacak
# fuel kategorize edilecek allen hocanƒ±n kodu ile
# consumption temizlenip kategorize edilecek
# co2_emission temizlenip integer a evrilecek
# emission_class deƒüerleri hepsi aynƒ± gibi silinebilir fiyata etkisine bakƒ±lacak
# comfort&convenience puanlama mantƒ±ƒüƒ± yapƒ±labilir
# entertainment&media puanlama mantƒ±ƒüƒ± yapƒ±labilir
# safety_&_security puanlama mantƒ±ƒüƒ± yapƒ±labilir
# extras puanlama mantƒ±ƒüƒ± yapƒ±labilir
# description d√º≈ü√ºlecek
# emission_label null deƒüer √ßok fazla d√º≈ü√ºlebilir 
# gears tmizlenecek extreme deƒüerler var null deƒüer fazla
# country_version vat s√ºtunu ile deƒüerlendirilecek null lar dolacak
# electricity_consumption d√º≈üecek 
# last_service_date d√º≈üecek
# other_fuel_types d√º≈üecek
# availability d√º≈üecek
# last_timing_belt_service_date d√º≈üecek 
# available_from d√º≈üecek

In [765]:
df.first_registration.sample(60)

10669    [\n, 2016, \n]
1567     [\n, 2019, \n]
11312    [\n, 2017, \n]
1256     [\n, 2017, \n]
7079     [\n, 2018, \n]
6867     [\n, 2017, \n]
11911    [\n, 2018, \n]
4610     [\n, 2019, \n]
5351                NaN
5646                NaN
7819     [\n, 2019, \n]
11253    [\n, 2017, \n]
13224    [\n, 2018, \n]
7215     [\n, 2018, \n]
11203    [\n, 2016, \n]
2779     [\n, 2016, \n]
8866     [\n, 2016, \n]
7035     [\n, 2018, \n]
9586     [\n, 2018, \n]
6990     [\n, 2017, \n]
7694     [\n, 2019, \n]
12056    [\n, 2018, \n]
15302    [\n, 2019, \n]
7870                NaN
9023     [\n, 2016, \n]
10717    [\n, 2016, \n]
14113    [\n, 2018, \n]
10886    [\n, 2016, \n]
6031     [\n, 2016, \n]
1897     [\n, 2019, \n]
6608     [\n, 2018, \n]
2583     [\n, 2019, \n]
1079     [\n, 2018, \n]
9066     [\n, 2016, \n]
15769    [\n, 2019, \n]
10171    [\n, 2019, \n]
1618     [\n, 2018, \n]
4040     [\n, 2017, \n]
10852    [\n, 2016, \n]
10944    [\n, 2016, \n]
6284     [\n, 2016, \n]
879      [\n, 2017, \n]
7503     [\n, 2018, \n]
6038     [\n, 2016, \n]
5359     [\n, 2019, \n]
4255     [\n, 2017, \n]
1948                NaN
12502    [\n, 2019, \n]
15719    [\n, 2018, \n]
14899    [\n, 2019, \n]
10998    [\n, 2017, \n]
1183     [\n, 2017, \n]
14978    [\n, 2016, \n]
673      [\n, 2016, \n]
7237     [\n, 2018, \n]
5051                NaN
2036                NaN
2482     [\n, 2019, \n]
10040    [\n, 2019, \n]
14038    [\n, 2017, \n]
Name: first_registration, dtype: object

In [766]:
check_df("registration")

column name :  registration
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64
******************************

In [767]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  type                           15917 non-null  object
 12  previous_owners                9279 non-null   object
 13  next_inspection                3535 non-null   object
 14  inspection_new                 3932 non-null   object
 15  warranty                       10499 non-null  object
 16  full_service                   8215 non-null   object
 17  non_smoking_vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  make                           15919 non-null  object
 20  model                          15919 non-null  object
 21  offer_number                   12744 non-null  object
 22  first_registration             14322 non-null  object
 23  body_color                     15322 non-null  object
 24  paint_type                     10147 non-null  object
 25  body_color_original            12160 non-null  object
 26  upholstery                     12199 non-null  object
 27  body                           15859 non-null  object
 28  nr_of_doors                    15707 non-null  object
 29  nr_of_seats                    14942 non-null  object
 30  model_code                     4978 non-null   object
 31  gearing_type                   15919 non-null  object
 32  displacement                   15423 non-null  object
 33  cylinders                      10239 non-null  object
 34  weight                         8945 non-null   object
 35  drive_chain                    9061 non-null   object
 36  fuel                           15919 non-null  object
 37  consumption                    14013 non-null  object
 38  co2_emission                   14111 non-null  object
 39  emission_class                 12898 non-null  object
 40  comfort&convenience            14999 non-null  object
 41  entertainment&media            14545 non-null  object
 42  extras                         12957 non-null  object
 43  safety_&_security              14937 non-null  object
 44  description                    15919 non-null  object
 45  emission_label                 3985 non-null   object
 46  gears                          11207 non-null  object
 47  country_version                7586 non-null   object
 48  electricity_consumption        137 non-null    object
 49  last_service_date              566 non-null    object
 50  other_fuel_types               880 non-null    object
 51  availability                   635 non-null    object
 52  last_timing_belt_service_date  16 non-null     object
 53  available_from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [768]:
# 1. url column

In [769]:
check_df(["url"])

column name :  ['url']
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % url    0.0
dtype: float64
Num_of_Nulls   :  url    0
dtype: int64
url
https://www.autoscout24.com//offers/audi-a1-1-0-30-tfsi-sportback-advanced-2019-sh-pdc-gasoline-white-1037d13f-0851-44dd-b559-c6f6def8e6d2                     1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-s-s-innovation-at-matrix-led-gasoline-black-8b880006-0c08-4500-91c0-2b45013716c8                   1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-innovation-matrix-navi-pdc-gasoline-silver-bf9ce61b-6d07-4e1a-b734-e5c1742f03b8                    1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-innovation-navi-klimaaut-gasoline-blue-900ec5a8-b2db-427d-8977-8363b8ae15b9                        1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-innovation-navi-klimaaut-gasoline-grey-913b914f-a839-416d-96ba-c995de9f4db3                        1
                                                                                                                                                              ..
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-1-5-150-ps-euro-6-wltp-gasoline-white-d84d9ed1-c735-48a1-89ba-d614f7da6a0a                       1
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-110kw-gasoline-00a371f2-061f-4339-87cd-f5605edae75b                                              1
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-150-gps-radars-16p-gasoline-black-2f028979-a6f3-4716-9c76-6e981fb0a3c9                           1
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-150-gps-radars-16p-gasoline-grey-a6344f21-90da-4140-b505-9bd31ec5013e                            1
https://www.autoscout24.com//offers/renault-espace-zu-spaet-geht-an-haendler-da-wird-er-dann-23-000-ko-gasoline-silver-93caa088-19e3-905e-e053-e250040a8d8d    1
Length: 15919, dtype: int64
******************************

In [770]:
# 2. make_model column   # 19. make    # 20. model

In [771]:
check_df(["make_model"])

column name :  ['make_model']
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % make_model    0.0
dtype: float64
Num_of_Nulls   :  make_model    0
dtype: int64
make_model
Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
dtype: int64
******************************

In [772]:
df.make_model.str.split(" ", expand=True)

             0       1
0         Audi      A1
1         Audi      A1
2         Audi      A1
3         Audi      A1
4         Audi      A1
...        ...     ...
15914  Renault  Espace
15915  Renault  Espace
15916  Renault  Espace
15917  Renault  Espace
15918  Renault  Espace

[15919 rows x 2 columns]

In [773]:
df[["make", "model"]] = df.make_model.str.split(" ", expand=True)

In [774]:
# we can drop the make_model column
df.drop(columns="make_model", inplace=True)

In [775]:
df.head()

,url,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,VAT deductible,"56,013 km",01/2016,2 previous owners,NaN,66 kW,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500,Price negotiable,"80,000 km",03/2017,None,NaN,141 kW,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,VAT deductible,"83,450 km",02/2016,1 previous owner,NaN,85 kW,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500,None,"73,000 km",08/2016,1 previous owner,NaN,66 kW,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,"16,200 km",05/2016,1 previous owner,NaN,66 kW,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [776]:
# 3. short_description

In [777]:
get_diff_category_column(df["short_description"])

{0: '',
 1: '(2) 1.4 TDI ULTRA 90 AMBIENTE S tronic',
 2: '(2) 1.6 CDTI 136 ELITE AUTO',
 3: '(3E GENERATION) III (2) 1.6 TDI 110 BUSINESS LINE',
 4: '(4) Air Energy dCi 75',
 5: '(70 PS)/Radio/Klima/BT/CD',
 6: '(90 PS)/Klima/PDC/Radio/SHZ',
 7: '(K',
 8: '(Klim',
 9: '(RESERVADO)1.3CDTI 95CV/S&S/LL 15"/LED/BLUETOOTH',
 10: '(‚Ç¨15900',
 11: '(‚Ç¨5250',
 12: '(‚Ç¨5600',
 13: '(‚Ç¨8600',
 14: '(‚Ç¨8900',
 15: '(‚Ç¨8950',
 16: '(‚Ç¨9250',
 17: ')',
 18: '0 66kW Klima',
 19: '0 AT INNOVATION AFL',
 20: '0 Autom. MATRIX OPC',
 21: '0 Blue dCi 200 PS EDC',
 22: '0 CDTI 125 KW EU6 AT Innovation SHZ Alu',
 23: '0 CDTI Aut 4x4 Innovat Xen Navi Leder',
 24: '0 CDTI Aut Navi Bi-Xe Led E6',
 25: '0 CDTI BlueInj Ultimate',
 26: '0 CDTI BlueInjection Dynamic St./St. Aut',
 27: '0 CDTI BlueInjection Innovation S./S. Sy. Au',
 28: '0 CDTI BlueInjection Innovation St',
 29: '0 CDTI BlueInjection Innovation St./St. Aut',
 30: '0 CDTI BlueInjection Innovation St./St. Syst',
 31: '0 CDTI Blueinj. Aut',
 32: '0 CDTI Ecotec Allrad Aut',
 33: '0 CDTI Ecotec Allrad Cosmo Aut.**Aktio',
 34: '0 CDTI Ecotec Allrad Edition Aut',
 35: '0 CDTI Ecotec Allrad Start/Stop',
 36: '0 CDTI Ecotec Business Edition Aut',
 37: '0 CDTI INNOVATION LED',
 38: '0 CDTI Inno. EURO6',
 39: '0 CDTI Innovatio',
 40: '0 CDTI Innovation EURO6',
 41: '0 CDTI ST Edition *Aut./Navi',
 42: '0 CDTI Sport *ALU*KLIMA*NAVI*AHK',
 43: '0 CDTI ecoflex COSMO Start/Stop System',
 44: '0 CDTI*XENON*RFK*SITZH.*EU6',
 45: '0 Diesel S/S Innovation ST AT',
 46: '0 Easytronic/Klimaautomatik/Fron/R√ºckfahrkame',
 47: '0 Ecotec 66kW Klima',
 48: '0 L3 85 DSG MY 19',
 49: '0 Ltr. - 85 kW TFSI 85 kW (116 P',
 50: '0 S/S Klima',
 51: '0 Selection Start/Stop Klima',
 52: '0 T Business',
 53: '0 T Business 5-t√ºr. Navi DAB OnStar',
 54: '0 T Navi',
 55: '0 TDI',
 56: '0 TDI Attraction S tronic Navi',
 57: '0 TDI Euro.6-Exclusiv Umbau-S.Tronic-Navi',
 58: '0 TDI Gletcherwei√ü/Bluetooth/PDC',
 59: '0 TDI Intense S-tronic*1.BESITZ',
 60: '0 TDI SB Attr S-tron EU6 Navi/SHZ/Temp/BT',
 61: '0 TFSI',
 62: '0 TFSI *Navi*SHZ*PDC*GRA',
 63: '0 TFSI *SHZ*GRA*PDC*TEL',
 64: '0 TFSI - Matrix - Pano - VC - Garantie',
 65: '0 TFSI 115 PS',
 66: '0 TFSI 85 kW Navi/S-tronic/Xeno',
 67: '0 TFSI >Xenon/SHZ/1 FZG-Halter<',
 68: '0 TFSI Design * Facelift * 1.Besitz * LED',
 69: '0 TFSI Design *NEUWERTIG* XENON-LED',
 70: '0 TFSI MMI SHZ KLIMAAUT. PDC',
 71: '0 TFSI Navi Tempomat Sitzheizung',
 72: '0 TFSI S-TRONIC ULTRA NAVI SITZHEIZUNG',
 73: '0 TFSI S-tronic NAVIVOR. SHZ KLI',
 74: '0 TFSI Sport 5-Gg. NAV',
 75: '0 TFSI Sport 5-Gg. SH/PDC',
 76: '0 TFSI Sport Navi Xeno',
 77: '0 TFSI Sport Navi Xenon Alu17',
 78: '0 TFSI Sport S tronic Navi',
 79: '0 TFSI Sport S tronic media Paket',
 80: '0 TFSI Sport S-Line',
 81: '0 TFSI Sport S-Tronic Navi Xeno',
 82: '0 TFSI Sport Sitzhzg',
 83: '0 TFSI Sportback intense',
 84: '0 TFSI Sportback-KLIMAAUT-PDC-4xEFH-S&S-SHZ',
 85: '0 TFSI intense',
 86: '0 TFSI intense S-tronic',
 87: '0 TFSI intro',
 88: '0 TFSI sport *Xeno',
 89: '0 TFSI ultra 5-Gang',
 90: '0 TFSI ultra S tronic KLIMA',
 91: '0 Turbo 120 Jahre',
 92: '0 Turbo 120 Jahre Edition + 5 Jahre Garantie + A',
 93: '0 Turbo 90 PS 5-trg',
 94: '0 Turbo Dir. Inj. St./St. ECOTEC 120 Jahre Edit',
 95: '0 Turbo ECOTEC 120 Jahre Editio',
 96: '0 Turbo ECOTEC Cool&Sound',
 97: '0 Turbo ECOTEC Direct Injection Editio',
 98: '0 Turbo ECOTEC Direct Injection √ñsterreich Edit',
 99: '0 Turbo ECOTEC √ñsterreich Editio',
 100: '0 Turbo Eco S/S Innovation AT',
 101: '0 Turbo Ecot Dir. Inj. √ñsterr. Edition S/S',
 102: '0 Turbo Ecotec Cool&Sound *LP -29%',
 103: '0 Turbo Ecotec Di Inj. √ñsterreich Edition St',
 104: '0 Turbo Ecotec Dir. Inj. Cool&Sound Easytr. St',
 105: '0 Turbo Ecotec Dir. Inj. √ñsterreich Edition St',
 106: '0 Turbo Ecotec Direct Inj. Cool&Sound S/S',
 107: '0 Turbo Ecotec Direct Inj. Edition S/S',
 108: '0 Turbo Ecotec Direct Inj. √ñsterreich Editio',
 109: '0 Turbo Ecotec Direct Injection Cool&Sound St',
 110: '0 Turbo Ecotec EDITION 105 PS',
 111: '0 Turbo Innovation -43%',
 112: '0 Turbo Klima',
 113: '0 Turbo ecoflex Dir. Inj. Edition Easytr. St./S',
 114: '0 Turbo ecoflex Direct Inj. Cool&Sound St./S',
 115: '0 Turbo ecoflex Direct Injection Cool&Sou',
 116: '0 Turbo ecoflex Direct Injection Cool&Sound St',
 117: '0 Turbo ecoflex Direct Injection Edition S',
 118: '0 Turbo ecoflex Direct Injection Edition St./St',
 119: '0.9 TCe',
 120: '0.9 TCe 90cv Energy Expressio',
 121: '0.9 TCe 90eco Klima Anh√§ngerkpl. ParkPilot',
 122: '0.9 TCe Advantage - 36',
 123: '0.9 TCe Advantage - Remise 35',
 124: '0.9 TCe Energy Iconic',
 125: '0.9 TCe Energy Intens',
 126: '0.9 TCe Energy Limited',
 127: '0.9 TCe Garantie 5 ans Advantage - Remise 34',
 128: '0.9 Tce 75CV Life 5Pt',
 129: '0.9Tce 75CV Life 5Pt',
 130: '00 Euros HTVA',
 131: '00Euros HTVA',
 132: '050-5885615 Beste deal',
 133: '0CDTI Country Ecoflex Navi/Leder/Xeno',
 134: '0CDTI Ecotec Edition Aut',
 135: '0CDTI GS INNOVATION+STANDHEIZUNG+ LED',
 136: '0T NAVI',
 137: '0TDI Sportback Neues Modell 1.Hd/Autom./Xe',
 138: '0TFSI media-Paket/SHZ/PDC',
 139: '0dCi 200PS EDC E6dT',
 140: '0l Innovation AHK abn. SHZ PDC R√ºckfahrkam. X',
 141: '0l Innovation Navi Kamera elektr.Heckklappe',
 142: '1',
 143: '1 4 66kW (90CV) Color Editio',
 144: '1 4 66kW (90CV) Design Line',
 145: '1 4 66kW (90CV) Selective',
 146: '1 4 90 CV Selective',
 147: '1 4 Auto 66kW (90CV) Selective',
 148: '1 4 Turbo 74kW (100CV) S/S Selective',
 149: '1 4 Turbo S/S 110kW (150CV) Dynamic',
 150: '1 4 Turbo S/S 110kW ST Excellence',
 151: '1 4 Turbo S/S 125 CV ST Selective',
 152: '1 4 Turbo S/S 125 CV Selective',
 153: '1 4 Turbo S/S 92kW (125CV) SIGHT&CONNECT',
 154: '1 4 Turbo S/S 92kW (125CV) Selective',
 155: '1 4T 100CV Selective',
 156: '1 6 CDTI 136CV Excellence',
 157: '1 6 CDTi 100kW (136CV) Auto Excellence',
 158: '1 6 CDTi 100kW Auto 17/18 ST Excellence',
 159: '1 6 CDTi 100kW S&S TURBO D Selective',
 160: '1 6 CDTi 81kW (110CV) Dynamic',
 161: '1 6 CDTi 81kW (110CV) Selective',
 162: '1 6 CDTi S/S 100kW (136CV) ST Dynamic',
 163: '1 6 CDTi S/S 81kW (110CV) Selective',
 164: '1-HAND',
 165: '1-HAND/TUV AU NEU/ TOP ZUSTAND',
 166: '1. Hand',
 167: '1.0 (105pk)S/S*Edition*Navi/17¬®alu/airco/pdc/demow',
 168: '1.0 12V Centennial Ed. Registratie 2019 Nieuw',
 169: '1.0 30 TFSI Sportback Advanced',
 170: '1.0 30 TFSI Sportback Advanced 2019 SH PDC',
 171: '1.0 30 TFSI Sportback Basis',
 172: '1.0 30 TFSI Sportback Basis 2019 Navi Virtual',
 173: '1.0 30 TFSI Sportback Basis 2019 PDC SH',
 174: '1.0 30 TFSI Sportback S-Line',
 175: '1.0 30 TFSI Sportback S-Line 2019 SH PDC',
 176: '1.0 30TFSI Sportback Advanced 2019 Navi Virtu',
 177: '1.0 30TFSI Sportback S-Line 2019 Navi Virtual',
 178: '1.0 82 CV TFSI Neopatentati',
 179: '1.0 DI Turbo 105PS',
 180: '1.0 DI Turbo ecoFLEX Selection*Klima*USB',
 181: '1.0 ECOTEC Turbo On ONSTAR W-LAN EU6',
 182: '1.0 EDITION AUTOMAAT | RIJKLAARPRIJS | Intellilink',
 183: '1.0 Editio',
 184: '1.0 Edition 105Pk Automaat',
 185: '1.0 Edition BLUETOOTH PARKPILOT',
 186: '1.0 Edition IntelliLink Aut',
 187: '1.0 Edition Navigatie',
 188: '1.0 Edition SHZ/LHZ Frontkamera Klima-AT',
 189: '1.0 Edition/AUTOMAAT/NAVIGATIE/CLIMA',
 190: '1.0 Innovatio',
 191: '1.0 Innovation Easytronic Automaat',
 192: '1.0 Innovation NAVI CLIMA LANE ASSIST 17"LMV PDC',
 193: '1.0 Online Editio',
 194: '1.0 S-Line Edition 95cv Bicolor (SCONTO 19',
 195: '1.0 SBACK TFSI DESIGN 82 CV NEOPATENTATI',
 196: '1.0 ST EASYTRONIC 105PK',
 197: '1.0 ST ON Navi RFK Radar DAB+ Parkassist',
 198: '1.0 Selection - Klima Bluetooth el.FH',
 199: '1.0 Sportback BLUETOOTH/SHZ/PDC',
 200: '1.0 Sportback TFSI Adrenali',
 201: '1.0 T Comfort',
 202: '1.0 T EDITION +PDC+NAVI VIA HANDY+KLIMA',
 203: '1.0 T S/S 120 Jahre',
 204: '1.0 TFSI',
 205: '1.0 TFSI "Nieuwe St.!!"Superdeal!Fabr.Gar.07/2021',
 206: '1.0 TFSI (8X) Sportback ultra',
 207: '1.0 TFSI *PDC*SHZ*Klimaautomatik',
 208: '1.0 TFSI - Facelift',
 209: '1.0 TFSI - GARANTIE 12M',
 210: '1.0 TFSI 116 CLIM AUTO XENON CARPLAY RADAR JA16',
 211: '1.0 TFSI 5-Gang',
 212: '1.0 TFSI 5-Gang ultra NAVI/ SITZHEIZUNG',
 213: '1.0 TFSI 5-t√ºrer Klima Sitzheizung',
 214: '1.0 TFSI 8X Sportback design ultra',
 215: '1.0 TFSI 95pk + Cruise Control + 15" LMV',
 216: '1.0 TFSI 95pk Adrenalin S-line',
 217: '1.0 TFSI 95pk Automaat Adrenali',
 218: '1.0 TFSI ADRENALIN SPORTBACK 95 5P',
 219: '1.0 TFSI ALU+KLIMA+PDC+SHZ',
 220: '1.0 TFSI Adrenali',
 221: '1.0 TFSI Adrenalin 70 kW (95 C',
 222: '1.0 TFSI Adrenalin 70 kW (95 CV)',
 223: '1.0 TFSI Adrenalin S tronic 70 kW (95 CV)',
 224: '1.0 TFSI Attractio',
 225: '1.0 TFSI Austria',
 226: '1.0 TFSI Automaat Adrenalin S-Line Navi 17"LM/PDC',
 227: '1.0 TFSI Automatic Sommer-/Winterreife',
 228: '1.0 TFSI Business NAVI',
 229: '1.0 TFSI Business S-Tronic 116cv',
 230: '1.0 TFSI Concert Connect',
 231: '1.0 TFSI Concert Connect Klima GRA Bluetooth',
 232: '1.0 TFSI Desig',
 233: "1.0 TFSI Design Con NAVIGATORE '5764",
 234: '1.0 TFSI Design S Tronic 70 kW (95 CV)',
 235: '1.0 TFSI EU6D-T SPORTBACK 30 TFSI SPORT',
 236: '1.0 TFSI Isofix-Aufnahme Klimaanlage',
 237: '1.0 TFSI KLIMA+NAVI+EINPARKH. PLUS',
 238: '1.0 TFSI KLIMA+TEMPOMAT+ELEKTR.FENSTER',
 239: '1.0 TFSI KLIMAANLAGE PDC KOMFORT PAKET 1.HAND',
 240: '1.0 TFSI Klima',
 241: '1.0 TFSI Klima Alu CD Media Paket Start/Stop 5-Ga',
 242: '1.0 TFSI Klima Dynamik-Fahrwerk Sportlenkrad',
 243: '1.0 TFSI Klimaanlage Zentraverriegelung',
 244: '1.0 TFSI LimS5 Sportback basis ultra Navi',
 245: '1.0 TFSI Limousine',
 246: '1.0 TFSI Limousine S tronic desig',
 247: '1.0 TFSI Limousine S tronic sport',
 248: '1.0 TFSI Limousine Sport',
 249: '1.0 TFSI Limousine sport',
 250: '1.0 TFSI Multif.Lenkrad Klimaautom. Sitzheizun Tem',
 251: '1.0 TFSI Navi',
 252: '1.0 TFSI Navi Multif.Lenkrad Klimaautom. Sitzheizu',
 253: '1.0 TFSI Navi+Xenon+Einparkhilfe plus',
 254: '1.0 TFSI PDC LM Klima',
 255: '1.0 TFSI Pro95PK',
 256: '1.0 TFSI S LINE ADMIRED PDC XENON',
 257: '1.0 TFSI S LINE S TRONIC SPORTBACK Navi HALFLEDER',
 258: '1.0 TFSI S Tronic Sport | Navi | Xenon Plus',
 259: '1.0 TFSI S line LED KLIMA RDC AUX USB MP3',
 260: '1.0 TFSI S line Navi LED-hinten Multif.Lenkrad Kli',
 261: '1.0 TFSI S line S-tronic Navi|Pano|Xenon|LED',
 262: '1.0 TFSI S tronic',
 263: '1.0 TFSI S tronic Navi Automatik Sitzh',
 264: '1.0 TFSI S tronic Sportback',
 265: '1.0 TFSI S tronic ultra Navi LM Klima',
 266: '1.0 TFSI S-tronic NAVI KLIMA SHZ',
 267: '1.0 TFSI S-tronic*S-line*Xenon*PDC*SHZ*17Zoll',
 268: '1.0 TFSI SB sport Sitzheizung',
 269: '1.0 TFSI SHZ Connectivity-Paket',
 270: '1.0 TFSI Spb. design - Navi - DAB - PDC - ALU',
 271: '1.0 TFSI Sport',
 272: '1.0 TFSI Sport *NAVIvorb*SHZ*KLIMAAUT',
 273: '1.0 TFSI Sport Klima Sitzhzg. Navivorber',
 274: '1.0 TFSI Sport Pro L',
 275: '1.0 TFSI Sport S tronic',
 276: '1.0 TFSI Sport S tronic *NAVI*PDC*SHZ',
 277: '1.0 TFSI Sport admired und active style',
 278: '1.0 TFSI Sport ultra Xenon PDC Media Paket',
 279: '1.0 TFSI Sportback',
 280: '1.0 TFSI Sportback Klimaautomatik Sitzheizung',
 281: '1.0 TFSI Sportback MMI elek. Au√üenspiegel',
 282: '1.0 TFSI Sportback Navi',
 283: '1.0 TFSI Sportback Navigation Klima Regensenso',
 284: '1.0 TFSI Sportback PDC SH MMI Xeno',
 285: '1.0 TFSI Sportback PDC SH MMI Xenon Navi Alu',
 286: '1.0 TFSI Sportback S line NAVI LED KLIMA RDC',
 287: '1.0 TFSI Sportback S tronic',
 288: '1.0 TFSI Sportback S tronic Sline Ex Xenon Klima',
 289: '1.0 TFSI Sportback S-Line',
 290: '1.0 TFSI Sportback S-Line Automatik KlimaPDC',
 291: '1.0 TFSI Sportback SPORT XENON*SHZ*MMI',
 292: '1.0 TFSI Sportback Sport PDC SH MMI Xenon Alu',
 293: '1.0 TFSI Sportback Ultra Adrenalin km zero',
 294: '1.0 TFSI Sportback XENON/SHZ/PDC/MMI',
 295: '1.0 TFSI Sportback basis KLIMA XENON',
 296: '1.0 TFSI Sportback basis ultra Klima PDC hi',
 297: '1.0 TFSI Sportback basis ultra S-Line',
 298: '1.0 TFSI Sportback ultra',
 299: '1.0 TFSI ULTRA CLIM/GPS/JA',
 300: '1.0 TFSI Ultra Climatronic Media Paket Alufelge',
 301: '1.0 TFSI Ultra NAVI',
 302: '1.0 TFSI Ultra*EURO6*Klimaautomatik*LM16',
 303: '1.0 TFSI XENON Einparkhilfe Sitzheizung USB',
 304: '1.0 TFSI XENON-PLUS*SZH*KLIMAAUTOMATIK',
 305: '1.0 TFSI admired Klima',
 306: '1.0 TFSI basis',
 307: '1.0 TFSI basis Klima',
 308: '1.0 TFSI basis Klima SHZ PDC hinte',
 309: '1.0 TFSI basis ultra Connectivity Sitzhz',
 310: '1.0 TFSI basis ultra USB PDC SHZ XENON EU6',
 311: '1.0 TFSI design Sportback Navi',
 312: '1.0 TFSI design ultra Connectivity Alu',
 313: '1.0 TFSI intense',
 314: '1.0 TFSI intro',
 315: '1.0 TFSI sport',
 316: '1.0 TFSI sport 1',
 317: '1.0 TFSI sport 3xSline LED Privacy NAVI Garantie',
 318: '1.0 TFSI sport Klimaanlage Telefo',
 319: '1.0 TFSI sport LM',
 320: '1.0 TFSI sport MMI Alu media-Paket Sportsitze',
 321: '1.0 TFSI sport Tempo PDC SHZ Klimaauto Alu',
 322: '1.0 TFSI sport XenonPlus Klima Sitzh. MMI',
 323: '1.0 TFSI sport ultra',
 324: '1.0 TFSI sport*S line*Navi*Tempomat*LED',
 325: '1.0 TFSI ultra',
 326: '1.0 TFSI ultra *8Fach Bereift*Klima*RADIO CD',
 327: '1.0 TFSI ultra *GRA*Klima',
 328: '1.0 TFSI ultra 60kW*EU6 plus*Bluet*SHZ*AMI*PD',
 329: '1.0 TFSI ultra ADMIRED ACTIVE',
 330: '1.0 TFSI ultra Anfahrassistent Sitzheizung',
 331: '1.0 TFSI ultra DAB Bluetooth Temp',
 332: '1.0 TFSI ultra Desig',
 333: '1.0 TFSI ultra Design - ALCANTARA',
 334: '1.0 TFSI ultra Design 25.000 KM COMME NEUVE',
 335: '1.0 TFSI ultra Design S tronic',
 336: '1.0 TFSI ultra Design XENON GPS CARPASS CARNET',
 337: '1.0 TFSI ultra KLIMA FSE SHZ EU6',
 338: '1.0 TFSI ultra KLIMA LM ZV',
 339: '1.0 TFSI ultra NAVI',
 340: '1.0 TFSI ultra Navi PDC Alu Sitzheizung',
 341: '1.0 TFSI ultra S line Navi',
 342: '1.0 TFSI ultra S line Sport s-tronic Navi Multif.L',
 343: '1.0 TFSI ultra S tronic Admired',
 344: '1.0 TFSI ultra S tronic sport',
 345: '1.0 TFSI ultra S tronic*Navi',
 346: '1.0 TFSI ultra S-tronic *Navi*Alu*Klima',
 347: '1.0 TFSI ultra Sport',
 348: '1.0 TFSI ultra Sport 5-Gg. SH/PDC',
 349: '1.0 TFSI ultra Sportback',
 350: '1.0 TFSI ultra Sportback "Klima+CD',
 351: '1.0 TFSI ultra Sportback *Klima*PDC*Media Paket',
 352: '1.0 TFSI ultra Sportback 7.985km Cruise PDC MF',
 353: '1.0 TFSI ultra Sportback Navi Audi Garantie',
 354: '1.0 TFSI ultra Sportback S tronic',
 355: '1.0 TFSI ultra Sportback S tronic AUTOMATIK NAVI L',
 356: '1.0 TFSI ultra Sportback S tronic desig',
 357: '1.0 TFSI ultra Sportback Sitzheizung Audi MMI',
 358: '1.0 TFSI ultra Sportback T√úV NEU',
 359: '1.0 TFSI ultra Sportback desig',
 360: '1.0 TFSI ultra Sportback design AUTOMATIK',
 361: '1.0 TFSI ultra Sportback sport',
 362: '1.0 TFSI ultra UNICO PROPRIETARIO!**SCONTATA',
 363: '1.0 TFSI ultra Xenon Navi Bluetooth APS-Plus Tempo',
 364: '1.0 TFSI ultra design Navi Sportsitze Sitzh. PD',
 365: '1.0 TFSI ultra design|Neuwagengeruch|Topzustand',
 366: '1.0 TFSI ultra design|Sitzhzg|PDC|MMI|16"Alu',
 367: '1.0 TFSI ultra sport',
 368: '1.0 TFSI ultra sport - Garantie 02/20 - Xenon - WR',
 369: '1.0 TFSI ultra sport S-Line Navi',
 370: '1.0 TFSI*NAVIGATIE*XENON*HANDVRIJ BELLEN',
 371: '1.0 TFSI*SPORTBACK*GPS*PDC*CARPASS*12M GARANTIE',
 372: '1.0 TFSI+ Xenon+PDC+ zetelverwarming+ garantie',
 373: '1.0 TFSi 115 Sportback + GPS Virtual + Xeno',
 374: '1.0 TFSi 115 Sportback + GPS Virtual + Xenon + Ada',
 375: '1.0 TFSi 115 Sportback + Xenon + Adaptiv Cruise',
 376: '1.0 TFSi Bluetooth Multilenkrad',
 377: '1.0 TFSi admired & active style Paket *159',
 378: '1.0 TFSi sport Navi Sitzhzg Multilenkrad Blue',
 379: '1.0 TSI',
 380: '1.0 TURBO *AUTOMAAT *NAVI *LEDER *INTELLILUX',
 381: '1.0 TURBO 5D EDITION + A/T + GPS + AIRCO + CRUISE',
 382: '1.0 TURBO**BERLINE**ESSENCE**GPS',
 383: '1.0 Tfsi 95cv Desig',
 384: '1.0 Turbo **10 330',
 385: '1.0 Turbo - Bluetooth',
 386: '1.0 Turbo 105 ch ECOTEC Start/Stop Editio',
 387: '1.0 Turbo 105c',
 388: '1.0 Turbo 105pk Online Edition Automaat Navigatie',
 389: '1.0 Turbo 120 Jaar Editio',
 390: '1.0 Turbo 120 Jahre',
 391: '1.0 Turbo 120 Jahre *Kamera*LED*Winterpak',
 392: '1.0 Turbo 5 t√ºr. PDC IntelliLink Sitzheizung',
 393: '1.0 Turbo AUTOMAAT Editio',
 394: '1.0 Turbo Active --DIENSTWAGENTAUSCH',
 395: '1.0 Turbo Automatik Dynamic',
 396: '1.0 Turbo Cosmo clim. multimedia. garantie 2ans',
 397: '1.0 Turbo ECOTEC Dynamic Start/Stop *GPS',
 398: '1.0 Turbo ECOTEC Edition Start/Stop',
 399: '1.0 Turbo Easytronic - Allwetterreife',
 400: '1.0 Turbo Easytronic Editio',
 401: '1.0 Turbo Easytronic Sports Tourer Dynamic Klima A',
 402: '1.0 Turbo Easytronic Start/Stop Dynamic',
 403: '1.0 Turbo Eco S/S Dynamic EasyTronic',
 404: '1.0 Turbo Eco S/S Edition IntelliLink SHZ',
 405: '1.0 Turbo Edition 5-t√ºrig',
 406: '1.0 Turbo Edition Easytronic Automatik',
 407: '1.0 Turbo Edition KLIMA PDC ONSTAR NAVI',
 408: '1.0 Turbo Edition ONSTAR NAVI W-LAN EU6',
 409: '1.0 Turbo Edition PDC INTELLILINK EU6',
 410: '1.0 Turbo Online Edition 2.0',
 411: '1.0 Turbo Parksens V+A/ Automaat + gratis Navi',
 412: '1.0 Turbo S/S Dynamic',
 413: '1.0 Turbo S/S Edition IntelliLink Sitzhzg',
 414: '1.0 Turbo S/S Edition Navi SHZ LkrHz ab 2',
 415: '1.0 Turbo S/S Expressio',
 416: '1.0 Turbo S/S Selective',
 417: '1.0 Turbo SGE 115CV Start&Stop Coup√© Co',
 418: '1.0 Turbo Selectio',
 419: '1.0 Turbo Sports Tourer Innovatio',
 420: '1.0 Turbo Start/Stop 120 Jahre',
 421: '1.0 Turbo Start/Stop Dynamic',
 422: '1.0 Turbo Start/Stop Editio',
 423: '1.0 Turbo Start/Stop ON AGR Navi SHZ LkrHz ab2',
 424: '1.0 Turbo Start/Stop Sports Tourer Active (K)',
 425: '1.0 Turbo ecoFLEX 5 porte Innovatio',
 426: '1.0 Turbo ecoFLEX Automatic Elective Park Navi',
 427: '1.0 Turbo ecoFLEX S&S aut. Sports Tourer Dynamic',
 428: '1.0 Turbo ecoFLEX Start',
 429: '1.0 Turbo ecoFLEX Start&Stop 5 porte Advance',
 430: '1.0 Turbo ecoFLEX Start&Stop EASYTRONIC Navi',
 431: '1.0 Turbo ecoFLEX Start&Stop aut. 5 porte Innovati',
 432: '1.0 Turbo √ñ-Edition 5-t√ºrig',
 433: '1.0 Turbo**10 330',
 434: '1.0 Turbo/ Break',
 435: '1.0 ecoflex',
 436: '1.0 ultra Sportback mit Klimaautomtik',
 437: '1.0*TFSi*KLIMA*GRA*MAL',
 438: '1.0B 120 YEARS EDITION * NAVI * PARKEERSENSOREN',
 439: '1.0T 105pk Edition 120Year +Navigatie+Sensore',
 440: '1.0T AUTOMAAT ONLINE EDITION',
 441: '1.0T Automaat INNOVATION +LED+Leder+Navigatie',
 442: '1.0T Dynamic |Opel OnStar| Detecci√≥n Se√±ales',
 443: '1.0T EDITION +PDC+NAVI VIA HANDY+KLIMA',
 444: '1.0T S&S EDITION +KLIMA+GRA+R4.0+PDC+BT',
 445: '1.0T S/S 120 Aniversario',
 446: '1.0T S/S Dynamic',
 447: '1.0T S/S Dynamic 105CV',
 448: '1.0T S/S ST Edition+ALW+R4.0+PDC+KLIM+GRA',
 449: '1.0T S/S Selective',
 450: '1.0T S/S Selective 105CV',
 451: '1.0TFSI',
 452: '1.0TFSI - 95 pk - S-LINE + Navigatie',
 453: '1.0TFSI - 95 pk - S-LINE + Navigatie - Xeno',
 454: '1.0TFSI 95PS NAVI.SITZHZG.AC-AUTOM.BLUETOOTH',
 455: '1.0TFSI Sportback Sport PDC SH MMI Xenon Navi',
 456: '1.0TFSI Sportback desig',
 457: '1.0TFSI Sportback/Navi/PDC/SHZ/ALU/MMI/Klimaa',
 458: '1.0TFSI Ultra Navi-Vorbereitung Klima',
 459: '1.0TFSI admired Sitzheizung Xeno',
 460: '1.0TFSI ultra Klimaanlage Zentralverriegelung',
 461: '1.0TFSI ultra Navi|ParkPilot|Sitzhzg',
 462: '1.0TSI Sportback MMI ParkPilot SHZ Alu',
 463: '1.1 75CV 5 porte Life',
 464: '1.2',
 465: '1.2 (69PS)',
 466: '1.2 (EURO 6d-TEMP) Bremsass Klima Radio BT',
 467: '1.2 **nur 8tkm** *Klimaanlage und Radio',
 468: '1.2 *Scheckheft* Klima*ZV-Funk*Radio*MP3',
 469: '1.2 - Life |16V-Klima-Tempomat-LED-USB-Gara',
 470: '1.2 16V 75 Advantage',
 471: '1.2 16V 75 LIFE',
 472: '1.2 16V 75 LIFE 5 P 9751 KMS',
 473: '1.2 16V 75 LIMITED',
 474: '1.2 16V 75 LIMITED *KLIMA*NAVI',
 475: '1.2 16V 75 LIMITED 2018',
 476: '1.2 16V 75 Life',
 477: '1.2 16V 75 Life > KLIMA',
 478: '1.2 16V 75 Life Cool & Sound',
 479: '1.2 16V 75 Limited',
 480: '1.2 16V 75 Limited Klima',
 481: '1.2 16V 75 Trend',
 482: '1.2 16V Advantage Klima-MFA-Multi-GRA',
 483: '1.2 16V Klima',
 484: '1.2 16V Limited Klimaanlage',
 485: '1.2 16v 5P B-Color OK neopatentati',

In [778]:
# 4. body type columns

In [779]:
check_df(["body_type"])

column name :  ['body_type']
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % body_type    0.38
dtype: float64
Num_of_Nulls   :  body_type    60
dtype: int64
body_type
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
dtype: int64
******************************

In [780]:
get_diff_category_column(df["body_type"])

{0: 'Compact',
 1: 'Convertible',
 2: 'Coupe',
 3: 'Off-Road',
 4: 'Other',
 5: 'Sedans',
 6: 'Station wago',
 7: 'Transporter',
 8: 'Va'}

In [781]:
# 5 price

In [782]:
check_df(["price"])

column name :  ['price']
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % price    0.0
dtype: float64
Num_of_Nulls   :  price    0
dtype: int64
price
14990    154
15990    151
10990    139
15900    106
17990    102
        ...
18977      1
18939      1
18925      1
18920      1
74600      1
Length: 2956, dtype: int64
******************************

In [783]:
df.rename(columns={"price": "price_‚Ç¨"}, inplace=True )

In [784]:
df["price_‚Ç¨"] = df["price_‚Ç¨"].astype(float)
# s√ºtunun veri tipini floata √ßevirmemiz gerekiyor.

In [785]:
df.info()
# price_‚Ç¨ tipinin deƒü≈ütiƒüini g√∂rd√ºk.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             15919 non-null  object
 6   registration                   15919 non-null  object
 7   prev_owner                     9091 non-null   object
 8   kW                             0 non-null      float64
 9   hp                             15919 non-null  object
 10  type                           15917 non-null  object
 11  previous_owners                9279 non-null   object
 12  next_inspection                3535 non-null   object
 13  inspection_new                 3932 non-null   object
 14  warranty                       10499 non-null  object
 15  full_service                   8215 non-null   object
 16  non_smoking_vehicle            7177 non-null   object
 17  null                           15919 non-null  object
 18  make                           15919 non-null  object
 19  model                          15919 non-null  object
 20  offer_number                   12744 non-null  object
 21  first_registration             14322 non-null  object
 22  body_color                     15322 non-null  object
 23  paint_type                     10147 non-null  object
 24  body_color_original            12160 non-null  object
 25  upholstery                     12199 non-null  object
 26  body                           15859 non-null  object
 27  nr_of_doors                    15707 non-null  object
 28  nr_of_seats                    14942 non-null  object
 29  model_code                     4978 non-null   object
 30  gearing_type                   15919 non-null  object
 31  displacement                   15423 non-null  object
 32  cylinders                      10239 non-null  object
 33  weight                         8945 non-null   object
 34  drive_chain                    9061 non-null   object
 35  fuel                           15919 non-null  object
 36  consumption                    14013 non-null  object
 37  co2_emission                   14111 non-null  object
 38  emission_class                 12898 non-null  object
 39  comfort&convenience            14999 non-null  object
 40  entertainment&media            14545 non-null  object
 41  extras                         12957 non-null  object
 42  safety_&_security              14937 non-null  object
 43  description                    15919 non-null  object
 44  emission_label                 3985 non-null   object
 45  gears                          11207 non-null  object
 46  country_version                7586 non-null   object
 47  electricity_consumption        137 non-null    object
 48  last_service_date              566 non-null    object
 49  other_fuel_types               880 non-null    object
 50  availability                   635 non-null    object
 51  last_timing_belt_service_date  16 non-null     object
 52  available_from                 272 non-null    object
dtypes: float64(2), object(51)
memory usage: 6.4+ MB

# 6. vat

In [786]:
check_df(["vat"])
# Data is clean already. We will fill the missing values

column name :  ['vat']
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % vat    28.35
dtype: float64
Num_of_Nulls   :  vat    4513
dtype: int64
vat
VAT deductible      10980
NaN                  4513
Price negotiable      426
dtype: int64
******************************

# 7. km

In [787]:
check_df("km")

column name :  km
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ...
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64
******************************

In [788]:

df['km'] = df['km'].str.replace(r'[^0-9]+', '')
df

C:\Users\Elitebook\AppData\Local\Temp\ipykernel_20596\787161897.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['km'] = df['km'].str.replace(r'[^0-9]+', '')

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,kW,hp,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013,01/2016,2 previous owners,NaN,66 kW,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000,03/2017,None,NaN,141 kW,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450,02/2016,1 previous owner,NaN,85 kW,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000,08/2016,1 previous owner,NaN,66 kW,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200,05/2016,1 previous owner,NaN,66 kW,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200CV EDC Executive 4Control,Van,39950.0,VAT deductible,,-/-,None,NaN,147 kW,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885.0,VAT deductible,9900,01/2019,1 previous owner,NaN,165 kW,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875.0,VAT deductible,15,03/2019,1 previous owner,NaN,146 kW,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700.0,VAT deductible,10,06/2019,None,NaN,147 kW,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999.0,VAT deductible,,01/2019,1 previous owner,NaN,165 kW,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [789]:
df.km = df.km.str.extract(r"(\d+)").astype(float)

In [790]:
df["km"]

0        56013.0
1        80000.0
2        83450.0
3        73000.0
4        16200.0
          ...
15914        NaN
15915     9900.0
15916       15.0
15917       10.0
15918        NaN
Name: km, Length: 15919, dtype: float64

In [791]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             14895 non-null  float64
 6   registration                   15919 non-null  object
 7   prev_owner                     9091 non-null   object
 8   kW                             0 non-null      float64
 9   hp                             15919 non-null  object
 10  type                           15917 non-null  object
 11  previous_owners                9279 non-null   object
 12  next_inspection                3535 non-null   object
 13  inspection_new                 3932 non-null   object
 14  warranty                       10499 non-null  object
 15  full_service                   8215 non-null   object
 16  non_smoking_vehicle            7177 non-null   object
 17  null                           15919 non-null  object
 18  make                           15919 non-null  object
 19  model                          15919 non-null  object
 20  offer_number                   12744 non-null  object
 21  first_registration             14322 non-null  object
 22  body_color                     15322 non-null  object
 23  paint_type                     10147 non-null  object
 24  body_color_original            12160 non-null  object
 25  upholstery                     12199 non-null  object
 26  body                           15859 non-null  object
 27  nr_of_doors                    15707 non-null  object
 28  nr_of_seats                    14942 non-null  object
 29  model_code                     4978 non-null   object
 30  gearing_type                   15919 non-null  object
 31  displacement                   15423 non-null  object
 32  cylinders                      10239 non-null  object
 33  weight                         8945 non-null   object
 34  drive_chain                    9061 non-null   object
 35  fuel                           15919 non-null  object
 36  consumption                    14013 non-null  object
 37  co2_emission                   14111 non-null  object
 38  emission_class                 12898 non-null  object
 39  comfort&convenience            14999 non-null  object
 40  entertainment&media            14545 non-null  object
 41  extras                         12957 non-null  object
 42  safety_&_security              14937 non-null  object
 43  description                    15919 non-null  object
 44  emission_label                 3985 non-null   object
 45  gears                          11207 non-null  object
 46  country_version                7586 non-null   object
 47  electricity_consumption        137 non-null    object
 48  last_service_date              566 non-null    object
 49  other_fuel_types               880 non-null    object
 50  availability                   635 non-null    object
 51  last_timing_belt_service_date  16 non-null     object
 52  available_from                 272 non-null    object
dtypes: float64(3), object(50)
memory usage: 6.4+ MB

In [792]:
# df.drop(columns="km_2", inplace=True)

In [793]:
df

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,kW,hp,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,01/2016,2 previous owners,NaN,66 kW,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,03/2017,None,NaN,141 kW,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,02/2016,1 previous owner,NaN,85 kW,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,08/2016,1 previous owner,NaN,66 kW,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,05/2016,1 previous owner,NaN,66 kW,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200CV EDC Executive 4Control,Van,39950.0,VAT deductible,NaN,-/-,None,NaN,147 kW,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885.0,VAT deductible,9900.0,01/2019,1 previous owner,NaN,165 kW,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875.0,VAT deductible,15.0,03/2019,1 previous owner,NaN,146 kW,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700.0,VAT deductible,10.0,06/2019,None,NaN,147 kW,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999.0,VAT deductible,NaN,01/2019,1 previous owner,NaN,165 kW,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

# 8. registration

In [794]:
check_df("registration")

column name :  registration
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64
******************************

In [795]:
df["registration"] = df.registration.str.extract(r"\d+/(\d*)")

In [796]:
df

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,kW,hp,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,2016,2 previous owners,NaN,66 kW,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,2017,None,NaN,141 kW,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,2016,1 previous owner,NaN,85 kW,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,2016,1 previous owner,NaN,66 kW,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,2016,1 previous owner,NaN,66 kW,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200CV EDC Executive 4Control,Van,39950.0,VAT deductible,NaN,NaN,None,NaN,147 kW,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885.0,VAT deductible,9900.0,2019,1 previous owner,NaN,165 kW,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875.0,VAT deductible,15.0,2019,1 previous owner,NaN,146 kW,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700.0,VAT deductible,10.0,2019,None,NaN,147 kW,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999.0,VAT deductible,NaN,2019,1 previous owner,NaN,165 kW,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [797]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             14895 non-null  float64
 6   registration                   14322 non-null  object
 7   prev_owner                     9091 non-null   object
 8   kW                             0 non-null      float64
 9   hp                             15919 non-null  object
 10  type                           15917 non-null  object
 11  previous_owners                9279 non-null   object
 12  next_inspection                3535 non-null   object
 13  inspection_new                 3932 non-null   object
 14  warranty                       10499 non-null  object
 15  full_service                   8215 non-null   object
 16  non_smoking_vehicle            7177 non-null   object
 17  null                           15919 non-null  object
 18  make                           15919 non-null  object
 19  model                          15919 non-null  object
 20  offer_number                   12744 non-null  object
 21  first_registration             14322 non-null  object
 22  body_color                     15322 non-null  object
 23  paint_type                     10147 non-null  object
 24  body_color_original            12160 non-null  object
 25  upholstery                     12199 non-null  object
 26  body                           15859 non-null  object
 27  nr_of_doors                    15707 non-null  object
 28  nr_of_seats                    14942 non-null  object
 29  model_code                     4978 non-null   object
 30  gearing_type                   15919 non-null  object
 31  displacement                   15423 non-null  object
 32  cylinders                      10239 non-null  object
 33  weight                         8945 non-null   object
 34  drive_chain                    9061 non-null   object
 35  fuel                           15919 non-null  object
 36  consumption                    14013 non-null  object
 37  co2_emission                   14111 non-null  object
 38  emission_class                 12898 non-null  object
 39  comfort&convenience            14999 non-null  object
 40  entertainment&media            14545 non-null  object
 41  extras                         12957 non-null  object
 42  safety_&_security              14937 non-null  object
 43  description                    15919 non-null  object
 44  emission_label                 3985 non-null   object
 45  gears                          11207 non-null  object
 46  country_version                7586 non-null   object
 47  electricity_consumption        137 non-null    object
 48  last_service_date              566 non-null    object
 49  other_fuel_types               880 non-null    object
 50  availability                   635 non-null    object
 51  last_timing_belt_service_date  16 non-null     object
 52  available_from                 272 non-null    object
dtypes: float64(3), object(50)
memory usage: 6.4+ MB

In [798]:
df.registration = df.registration.astype(float)

# 9 prev owner

In [799]:
check_df("prev_owner")

column name :  prev_owner
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 42.89
Num_of_Nulls   :  6828
1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64
******************************

In [800]:
df["prev_owner"] = df["prev_owner"].str.replace(r'[^0-9]+', '')

C:\Users\Elitebook\AppData\Local\Temp\ipykernel_20596\1887680495.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["prev_owner"] = df["prev_owner"].str.replace(r'[^0-9]+', '')

In [801]:
df

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,kW,hp,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,2016.0,2,NaN,66 kW,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,2017.0,None,NaN,141 kW,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,2016.0,1,NaN,85 kW,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,2016.0,1,NaN,66 kW,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,2016.0,1,NaN,66 kW,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200CV EDC Executive 4Control,Van,39950.0,VAT deductible,NaN,NaN,None,NaN,147 kW,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885.0,VAT deductible,9900.0,2019.0,1,NaN,165 kW,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875.0,VAT deductible,15.0,2019.0,1,NaN,146 kW,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700.0,VAT deductible,10.0,2019.0,None,NaN,147 kW,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999.0,VAT deductible,NaN,2019.0,1,NaN,165 kW,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [802]:
# df[‚Äúprev_owner‚Äù].str.extract(r"(\d+)")

# df[‚Äúprev_owner‚Äù].str.extract(r‚Äù(\D+)‚Äú)

In [803]:
df["prev_owner"] = df["prev_owner"].astype(float)
df

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,kW,hp,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,2016.0,2.0,NaN,66 kW,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,2017.0,NaN,NaN,141 kW,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,2016.0,1.0,NaN,85 kW,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,2016.0,1.0,NaN,66 kW,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,2016.0,1.0,NaN,66 kW,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200CV EDC Executive 4Control,Van,39950.0,VAT deductible,NaN,NaN,NaN,NaN,147 kW,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885.0,VAT deductible,9900.0,2019.0,1.0,NaN,165 kW,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875.0,VAT deductible,15.0,2019.0,1.0,NaN,146 kW,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700.0,VAT deductible,10.0,2019.0,NaN,NaN,147 kW,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999.0,VAT deductible,NaN,2019.0,1.0,NaN,165 kW,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

# 10 kw

In [804]:
check_df("kW")

column name :  kW
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 100.0
Num_of_Nulls   :  15919
NaN    15919
Name: kW, dtype: int64
******************************

In [805]:
df.drop(columns="kW", inplace=True)

In [806]:
df.head()

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,hp,type,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,2016.0,2.0,66 kW,"[, Used, , Diesel (Particulate Filter)]",...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,2017.0,NaN,141 kW,"[, Used, , Gasoline]",...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,2016.0,1.0,85 kW,"[, Used, , Diesel (Particulate Filter)]",...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,2016.0,1.0,66 kW,"[, Used, , Diesel (Particulate Filter)]",...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,2016.0,1.0,66 kW,"[, Used, , Diesel (Particulate Filter)]",...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

# 11. hp

In [807]:
check_df("hp")

column name :  hp
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ...
84 kW        1
195 kW       1
44 kW        1
239 kW       1
9 kW         1
Name: hp, Length: 81, dtype: int64
******************************

In [808]:
df["hp"] = df["hp"].str.extract(r"(\d+)").astype(float)

In [809]:
df.rename(columns={"hp":"hp_kW"}, inplace=True)

In [810]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 52 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             14895 non-null  float64
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   float64
 8   hp_kW                          15831 non-null  float64
 9   type                           15917 non-null  object
 10  previous_owners                9279 non-null   object
 11  next_inspection                3535 non-null   object
 12  inspection_new                 3932 non-null   object
 13  warranty                       10499 non-null  object
 14  full_service                   8215 non-null   object
 15  non_smoking_vehicle            7177 non-null   object
 16  null                           15919 non-null  object
 17  make                           15919 non-null  object
 18  model                          15919 non-null  object
 19  offer_number                   12744 non-null  object
 20  first_registration             14322 non-null  object
 21  body_color                     15322 non-null  object
 22  paint_type                     10147 non-null  object
 23  body_color_original            12160 non-null  object
 24  upholstery                     12199 non-null  object
 25  body                           15859 non-null  object
 26  nr_of_doors                    15707 non-null  object
 27  nr_of_seats                    14942 non-null  object
 28  model_code                     4978 non-null   object
 29  gearing_type                   15919 non-null  object
 30  displacement                   15423 non-null  object
 31  cylinders                      10239 non-null  object
 32  weight                         8945 non-null   object
 33  drive_chain                    9061 non-null   object
 34  fuel                           15919 non-null  object
 35  consumption                    14013 non-null  object
 36  co2_emission                   14111 non-null  object
 37  emission_class                 12898 non-null  object
 38  comfort&convenience            14999 non-null  object
 39  entertainment&media            14545 non-null  object
 40  extras                         12957 non-null  object
 41  safety_&_security              14937 non-null  object
 42  description                    15919 non-null  object
 43  emission_label                 3985 non-null   object
 44  gears                          11207 non-null  object
 45  country_version                7586 non-null   object
 46  electricity_consumption        137 non-null    object
 47  last_service_date              566 non-null    object
 48  other_fuel_types               880 non-null    object
 49  availability                   635 non-null    object
 50  last_timing_belt_service_date  16 non-null     object
 51  available_from                 272 non-null    object
dtypes: float64(5), object(47)
memory usage: 6.3+ MB

# 12. Type

In [811]:
check_df("type")

column name :  type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.01
Num_of_Nulls   :  2
[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: type, Length: 170, dtype: int64
******************************

In [812]:
get_diff_category_column(df.type)

{0: '',
 1: 'Biodiesel',
 2: 'Biogas',
 3: 'CNG',
 4: 'CNG (Particulate Filter)',
 5: 'Demonstratio',
 6: 'Diesel',
 7: 'Diesel (Particulate Filter)',
 8: 'Domestic gas H',
 9: 'Electric',
 10: 'Electric/Gasoline',
 11: "Employee's car",
 12: 'Gasoline',
 13: 'Gasoline (Particulate Filter)',
 14: 'LPG',
 15: 'Liquid petroleum gas (LPG)',
 16: 'New',
 17: 'Others',
 18: 'Others (Particulate Filter)',
 19: 'Pre-registered',
 20: 'Regular/Benzine 91',
 21: 'Regular/Benzine 91 (Particulate Filter)',
 22: 'Regular/Benzine E10 91',
 23: 'Regular/Benzine E10 91 (Particulate Filter)',
 24: 'Super 95',
 25: 'Super 95 (Particulate Filter)',
 26: 'Super E10 95',
 27: 'Super E10 95 (Particulate Filter)',
 28: 'Super Plus 98',
 29: 'Super Plus 98 (Particulate Filter)',
 30: 'Super Plus E10 98',
 31: 'Super Plus E10 98 (Particulate Filter)',
 32: 'Used'}

In [813]:
# Changing some columns value type from list to str
df = df.applymap(lambda x: ",".join(map(str,x)) if type(x) == list else x)
df.head()

,url,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,hp_kW,type,...,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,2016.0,2.0,66.0,",Used,,Diesel (Particulate Filter)",...,"\n,Sicherheit:, ,Deaktivierung f√ºr Beifahrer-A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,2017.0,NaN,141.0,",Used,,Gasoline",...,\nLangstreckenfahrzeug daher die hohe Kilomete...,\n4 (Green)\n,\n7\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,2016.0,1.0,85.0,",Used,,Diesel (Particulate Filter)",...,"\n,Fahrzeug-Nummer: AM-95365, ,Ehem. UPE 24.64...",\n4 (Green)\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,2016.0,1.0,66.0,",Used,,Diesel (Particulate Filter)",...,"\nAudi A1: ,- 1e eigenaar ,- Perfecte staat: s...",NaN,\n6\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,2016.0,1.0,66.0,",Used,,Diesel (Particulate Filter)",...,"\n,Technik & Sicherheit:,Xenon plus,Klimaautom...",NaN,NaN,\nGermany\n,NaN,NaN,NaN,NaN,NaN,NaN

In [814]:
check_df("type")

column name :  type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.01
Num_of_Nulls   :  2
,Used,,Diesel (Particulate Filter)                                                                                 3475
,Used,,Diesel                                                                                                      2516
,Used,,Gasoline                                                                                                    2367
,Used,,Super 95                                                                                                    1818
,Pre-registered,,Super 95                                                                                           500
                                                                                                                   ...
,New,,Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95       1
,Used,,Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)                               1
,Demonstration,,Super Plus 98                                                                                         1
,New,,Super Plus E10 98                                                                                               1
,Demonstration,,Regular/Benzine E10 91                                                                                1
Name: type, Length: 170, dtype: int64
******************************

In [815]:
df.type = df.type.str.extract(r",(\w+|\w+\W\w+|\w+\W\w\s\w+),")

In [816]:
df.type.sample(5)

660      Used
3159     Used
11018    Used
6037     Used
6346     Used
Name: type, dtype: object

In [817]:
df.type.unique()

array(['Used', "Employee's car", 'New', 'Demonstration', 'Pre-registered',
       nan], dtype=object)

In [818]:
df.type.value_counts()

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: type, dtype: int64

# 13 previous_owners

In [819]:
check_df("previous_owners")

column name :  previous_owners
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 41.71
Num_of_Nulls   :  6640
\n1\n                                                                               8103
NaN                                                                                 6640
\n2\n                                                                                766
\n0\n                                                                                163
\n3\n                                                                                 17
                                                                                    ...
\n1\n,\n111 g CO2/km (comb)\n                                                          1
\n1\n,\nEuro 6\n                                                                       1
\n2\n,\n119 g CO2/km (comb)\n                                                          1
\n1\n,\n,6.6 l/100 km (comb),\n,8.1 l/100 km (city),\n,5.7 l/100 km (country),\n       1
\n1\n,\n142 g CO2/km (comb)\n                                                          1
Name: previous_owners, Length: 102, dtype: int64
******************************

In [820]:
df.previous_owners = df.previous_owners.str.extract(r"(\d+)")

In [821]:
df.previous_owners.value_counts(dropna=False)

1      8294
NaN    6640
2       778
0       188
3        17
4         2
Name: previous_owners, dtype: int64

In [822]:
#Data is clean
#prev_owners and previous_owners will be controled and we will filled each other and dropped one of them.

In [823]:
check_df("prev_owner")

column name :  prev_owner
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 42.89
Num_of_Nulls   :  6828
1.0    8294
NaN    6828
2.0     778
3.0      17
4.0       2
Name: prev_owner, dtype: int64
******************************

In [824]:
df.previous_owners = df.previous_owners.astype(float)

# 14. next_inspection

In [825]:
check_df("next_inspection")

column name :  next_inspection
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 77.79
Num_of_Nulls   :  12384
NaN                                    12384
\n04/2022\n                               62
\n06/2021\n                               47
\n03/2021\n                               39
\n03/2022\n                               36
                                       ...
\n06/2021\n,\n121 g CO2/km (comb)\n        1
\n02/2020\n,\n139 g CO2/km (comb)\n        1
\n10/2021\n,\n136 g CO2/km (comb)\n        1
\n06/2019\n,\n139 g CO2/km (comb)\n        1
\n01/2022\n,\n168 g CO2/km (comb)\n        1
Name: next_inspection, Length: 1385, dtype: int64
******************************

In [826]:
df.drop(columns="next_inspection", inplace=True)
# it is not relevant to analysis bcs of that we can drop this column without cleaning

# 15 inspection_new

In [827]:
check_df("inspection_new")

column name :  inspection_new
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 75.3
Num_of_Nulls   :  11987
NaN                                                                                   11987
\nYes\n,\nEuro 6\n                                                                      523
\nYes\n                                                                                 442
\nYes\n,\n102 g CO2/km (comb)\n                                                         174
\nYes\n,\n4 (Green)\n                                                                   166
                                                                                      ...
\nYes\n,\n,5.2 l/100 km (comb),\n,6.7 l/100 km (city),\n,4.2 l/100 km (country),\n        1
\nYes\n,\n100 g CO2/km (comb)\n                                                           1
\nYes\n,\n,4.9 l/100 km (comb),\n,5.9 l/100 km (city),\n,4.3 l/100 km (country),\n        1
\nYes\n,\n,5.1 l/100 km (comb),\n,6.4 l/100 km (city),\n,4.3 l/100 km (country),\n        1
\nYes\n,\n172 g CO2/km (comb)\n                                                           1
Name: inspection_new, Length: 202, dtype: int64
******************************

In [828]:
df.drop(columns="inspection_new", inplace=True)
# it is not relevant to analysis bcs of that we can drop this column without cleaning

# 16 warranty

In [829]:
check_df("warranty")

column name :  warranty
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 34.05
Num_of_Nulls   :  5420
NaN                                                                                       5420
\n,\n,\nEuro 6\n                                                                          1868
\n12 months\n                                                                             1305
\n                                                                                         979
\n24 months\n                                                                              585
                                                                                          ...
\n2 months\n                                                                                 1
\n72 months\n,\n125 g CO2/km (comb)\n                                                        1
\n60 months\n,\n14 g CO2/km (comb)\n                                                         1
\n24 months\n,\n121 g CO2/km (comb)\n                                                        1
\n36 months\n,\n,7.4 l/100 km (comb),\n,9.6 l/100 km (city),\n,6 l/100 km (country),\n       1
Name: warranty, Length: 508, dtype: int64
******************************

In [830]:
df.warranty = df.warranty.str.extract(r"(\d+) months").astype(float)

In [831]:
df.warranty.value_counts().sort_index()

1.0        3
2.0        5
3.0       33
4.0        3
6.0      125
7.0        1
8.0        1
9.0        2
10.0       1
11.0       2
12.0    2594
13.0       3
14.0       2
15.0       1
16.0       4
17.0       2
18.0      10
19.0       3
20.0       7
21.0       2
22.0       2
23.0      11
24.0    1118
25.0       6
26.0       4
28.0       2
30.0       1
33.0       1
34.0       3
36.0     279
40.0       1
45.0       2
46.0       2
47.0       1
48.0     149
49.0       1
50.0       4
56.0       1
60.0     401
65.0       1
72.0      59
Name: warranty, dtype: int64

In [832]:
df[df.warranty == 12.0]["make"].value_counts()

Opel       1223
Audi        817
Renault     554
Name: make, dtype: int64

In [833]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             14895 non-null  float64
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   float64
 8   hp_kW                          15831 non-null  float64
 9   type                           15917 non-null  object
 10  previous_owners                9279 non-null   float64
 11  warranty                       4853 non-null   float64
 12  full_service                   8215 non-null   object
 13  non_smoking_vehicle            7177 non-null   object
 14  null                           15919 non-null  object
 15  make                           15919 non-null  object
 16  model                          15919 non-null  object
 17  offer_number                   12744 non-null  object
 18  first_registration             14322 non-null  object
 19  body_color                     15322 non-null  object
 20  paint_type                     10147 non-null  object
 21  body_color_original            12160 non-null  object
 22  upholstery                     12199 non-null  object
 23  body                           15859 non-null  object
 24  nr_of_doors                    15707 non-null  object
 25  nr_of_seats                    14942 non-null  object
 26  model_code                     4978 non-null   object
 27  gearing_type                   15919 non-null  object
 28  displacement                   15423 non-null  object
 29  cylinders                      10239 non-null  object
 30  weight                         8945 non-null   object
 31  drive_chain                    9061 non-null   object
 32  fuel                           15919 non-null  object
 33  consumption                    14013 non-null  object
 34  co2_emission                   14111 non-null  object
 35  emission_class                 12898 non-null  object
 36  comfort&convenience            14999 non-null  object
 37  entertainment&media            14545 non-null  object
 38  extras                         12957 non-null  object
 39  safety_&_security              14937 non-null  object
 40  description                    15919 non-null  object
 41  emission_label                 3985 non-null   object
 42  gears                          11207 non-null  object
 43  country_version                7586 non-null   object
 44  electricity_consumption        137 non-null    object
 45  last_service_date              566 non-null    object
 46  other_fuel_types               880 non-null    object
 47  availability                   635 non-null    object
 48  last_timing_belt_service_date  16 non-null     object
 49  available_from                 272 non-null    object
dtypes: float64(7), object(43)
memory usage: 6.1+ MB

# 17 full_service

In [834]:
check_df("full_service")

column name :  full_service
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 48.39
Num_of_Nulls   :  7704
NaN                                                                                 7704
\n,\n,\n4 (Green)\n                                                                 2235
\n,\n,\nEuro 6\n                                                                    2097
\n,\n                                                                               1702
\n,\n,\nEuro 6d-TEMP\n                                                               399
                                                                                    ...
\n,\n,\n80 g CO2/km (comb)\n                                                           1
\n,\n,\n84 g CO2/km (comb)\n                                                           1
\n,\n,\n,6 l/100 km (comb),\n,8 l/100 km (city),\n,4.9 l/100 km (country),\n           1
\n,\n,\n,4.9 l/100 km (comb),\n,6.2 l/100 km (city),\n,4.1 l/100 km (country),\n       1
\n,\n,\nEuro 4\n                                                                       1
Name: full_service, Length: 123, dtype: int64
******************************

In [835]:
df.drop(columns="full_service", inplace=True)

# 18 non_smoking_vehicle

In [836]:
check_df("non_smoking_vehicle")

column name :  non_smoking_vehicle
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 54.92
Num_of_Nulls   :  8742
NaN                                                                                 8742
\n,\n                                                                               3647
\n,\n,\n4 (Green)\n                                                                 1240
\n,\n,\nEuro 6\n                                                                    1127
\n,\n,\nEuro 6d-TEMP\n                                                               345
                                                                                    ...
\n,\n,\n,5.6 l/100 km (comb),\n,7.3 l/100 km (city),\n,4.7 l/100 km (country),\n       1
\n,\n,\n122 g CO2/km (comb)\n                                                          1
\n,\n,\n158 g CO2/km (comb)\n                                                          1
\n,\n,\n150 g CO2/km (comb)\n                                                          1
\n,\n,\n175 g CO2/km (comb)\n                                                          1
Name: non_smoking_vehicle, Length: 95, dtype: int64
******************************

In [837]:
df.drop(columns="non_smoking_vehicle", inplace=True)

# 19 null

In [838]:
df.drop(columns="null", inplace=True)

# 20 offer_number

In [839]:
df.drop(columns="offer_number", inplace=True)

# 21 first_registration

In [840]:
df.drop(columns="first_registration", inplace=True)

# 22 body_color

In [841]:
check_df("body_color")

column name :  body_color
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 3.75
Num_of_Nulls   :  597
\n,Black,\n     3745
\n,Grey,\n      3505
\n,White,\n     3406
\n,Silver,\n    1647
\n,Blue,\n      1431
\n,Red,\n        957
NaN              597
\n,Brown,\n      289
\n,Green,\n      154
\n,Beige,\n      108
\n,Yellow,\n      51
\n,Violet,\n      18
\n,Bronze,\n       6
\n,Orange,\n       3
\n,Gold,\n         2
Name: body_color, dtype: int64
******************************

In [842]:
df.body_color = df.body_color.str.split(",", expand=True)[1]

In [843]:
df.body_color.value_counts()

Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: body_color, dtype: int64

# 23 paint_type

In [844]:
check_df("paint_type")

column name :  paint_type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 36.26
Num_of_Nulls   :  5772
\nMetallic\n       9794
NaN                5772
\nUni/basic\n       347
\nPerl effect\n       6
Name: paint_type, dtype: int64
******************************

In [845]:
df.paint_type.str.extract(r"(\w+\W\w+|\w+)").value_counts(dropna=False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
dtype: int64

In [846]:
df.paint_type = df.paint_type.str.extract(r"(\w+\W\w+|\w+)")

# 24 body_color_original

In [847]:
check_df("body_color_original")

column name :  body_color_original
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 23.61
Num_of_Nulls   :  3759
NaN                                  3759
\nOnyx Schwarz\n                      338
\nBianco\n                            282
\nMythosschwarz Metallic\n            238
\nBrillantschwarz\n                   216
                                     ...
\nRouge-Braun (G0Y)\n                   1
\nVARI COLRI DISPONIBILI\n              1
\nKokosnussbraun Metallic\n             1
\nFarbe frei w√§hlbar\n                  1
\nPerlmutt-Wei√ü Metallic (Wei√ü)\n       1
Name: body_color_original, Length: 1928, dtype: int64
******************************

In [848]:
df.body_color_original.str.split("\n", expand=True)[1].value_counts()

Onyx Schwarz                     338
Bianco                           282
Mythosschwarz Metallic           238
Brillantschwarz                  216
Gris                             204
                                ...
Rouge-Braun (G0Y)                  1
VARI COLRI DISPONIBILI             1
Kokosnussbraun Metallic            1
Farbe frei w√§hlbar                 1
Perlmutt-Wei√ü Metallic (Wei√ü)      1
Name: 1, Length: 1927, dtype: int64

In [849]:
df.body_color_original = df.body_color_original.str.split("\n", expand=True)[1]

# 25 upholstery

In [850]:
check_df("upholstery")

column name :  upholstery
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 23.37
Num_of_Nulls   :  3720
\nCloth, Black\n           5821
NaN                        3720
\nPart leather, Black\n    1121
\nCloth\n                  1005
\nCloth, Grey\n             891
\nCloth, Other\n            639
\nFull leather, Black\n     575
\nBlack\n                   491
\nGrey\n                    273
\nOther, Other\n            182
\nPart leather\n            140
\nFull leather\n            139
\nFull leather, Brown\n     116
\nPart leather, Grey\n      116
\nOther, Black\n            110
\nFull leather, Other\n      72
\nFull leather, Grey\n       67
\nPart leather, Other\n      65
\nOther\n                    56
\nPart leather, Brown\n      50
\nalcantara, Black\n         47
\nVelour, Black\n            36
\nFull leather, Beige\n      36
\nCloth, Brown\n             28
\nVelour\n                   16
\nOther, Grey\n              15
\nCloth, Beige\n             13
\nBrown\n                    12
\nCloth, Blue\n              12
\nVelour, Grey\n              8
\nCloth, White\n              8
\nalcantara, Grey\n           6
\nCloth, Red\n                5
\nOther, Yellow\n             4
\nPart leather, Red\n         3
\nBeige\n                     3
\nPart leather, White\n       2
\nFull leather, Blue\n        2
\nalcantara, Other\n          2
\nalcantara\n                 2
\nWhite\n                     2
\nPart leather, Beige\n       2
\nBlue\n                      2
\nCloth, Orange\n             1
\nFull leather, Red\n         1
\nOther, Brown\n              1
\nFull leather, White\n       1
Name: upholstery, dtype: int64
******************************

In [851]:
df.upholstery.str.split("\n", expand=True)[1].str.extract(r"(\w+s?\w+)").value_counts()

Cloth        8423
Part         1499
Full         1009
Black         491
Other         368
Grey          273
Velour         60
alcantara      57
Brown          12
Beige           3
Blue            2
White           2
dtype: int64

In [852]:
df.upholstery = df.upholstery.str.split("\n", expand=True)[1].str.split(",", expand=True)[0]

In [853]:
df.upholstery.value_counts()

Cloth           8423
Part leather    1499
Full leather    1009
Black            491
Other            368
Grey             273
Velour            60
alcantara         57
Brown             12
Beige              3
Blue               2
White              2
Name: upholstery, dtype: int64

In [854]:
df.upholstery.unique()

array(['Cloth', nan, 'Part leather', 'Full leather', 'Black', 'Other',
       'alcantara', 'Velour', 'Grey', 'Blue', 'White', 'Beige', 'Brown'],
      dtype=object)

In [855]:
def upholsterytype(x):
    if x in Cloths:
        return "Cloth"
    elif x == "Full leather":
        return "Full leather"
    elif x == "Part leather":
        return "Part leather"
    elif x == "alcantara":
        return "alcantara"
    elif x== "Velour":
        return "Velour"
    elif x== "Other":
        return "Other"
    
df["upholstery"] = df.upholstery.apply(upholsterytype)

In [856]:
df.upholstery.value_counts(dropna=False)

Cloth           9206
NaN             3720
Part leather    1499
Full leather    1009
Other            368
Velour            60
alcantara         57
Name: upholstery, dtype: int64

# 26 Body

In [857]:
check_df("body")

column name :  body
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
\n,Sedans,\n           7903
\n,Station wagon,\n    3553
\n,Compact,\n          3153
\n,Van,\n               783
\n,Other,\n             290
\n,Transporter,\n        88
NaN                      60
\n,Off-Road,\n           56
\n,Coupe,\n              25
\n,Convertible,\n         8
Name: body, dtype: int64
******************************

In [858]:
df.body.str.strip("\n,").value_counts(dropna=False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body, dtype: int64

In [859]:
check_df("body_type")

column name :  body_type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64
******************************

In [860]:
df.drop(columns="body", inplace=True)

# 27 Nr. of Doors

In [861]:
check_df("nr_of_doors")

column name :  nr_of_doors
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 1.33
Num_of_Nulls   :  212
\n5\n    11575
\n4\n     3079
\n3\n      832
\n2\n      219
NaN        212
\n1\n        1
\n7\n        1
Name: nr_of_doors, dtype: int64
******************************

In [862]:
df.nr_of_doors = df.nr_of_doors.str.strip("\n")

In [863]:
df.nr_of_doors.value_counts()

5    11575
4     3079
3      832
2      219
1        1
7        1
Name: nr_of_doors, dtype: int64

In [864]:
df.nr_of_doors = df.nr_of_doors.astype(float)

# 28 Nr. of Seats

In [865]:
check_df("nr_of_seats")

column name :  nr_of_seats
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 6.14
Num_of_Nulls   :  977
\n5\n    13336
\n4\n     1125
NaN        977
\n7\n      362
\n2\n      116
\n6\n        2
\n3\n        1
Name: nr_of_seats, dtype: int64
******************************

In [866]:
df.nr_of_seats = df.nr_of_seats.str.strip("\n")

In [867]:
df.nr_of_seats.value_counts()

5    13336
4     1125
7      362
2      116
6        2
3        1
Name: nr_of_seats, dtype: int64

In [868]:
df.nr_of_seats = df.nr_of_seats.astype(float)

# 29 Model Code

In [869]:
check_df("model_code")

column name :  model_code
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 68.73
Num_of_Nulls   :  10941
NaN             10941
\n0035/BCB\n      268
\n0588/BNO\n      245
\n0588/BDB\n      206
\n0588/BHX\n      188
                ...
\n0035/AVN\n        1
\n0035/BEM\n        1
\n0035/BAG\n        1
\n0035/BAA\n        1
\n3333/BKG\n        1
Name: model_code, Length: 233, dtype: int64
******************************

In [870]:
df.drop(columns="model_code", inplace=True)

# 30 Gearing Type

In [871]:
check_df("gearing_type")

column name :  gearing_type
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
\n,Manual,\n            8153
\n,Automatic,\n         7297
\n,Semi-automatic,\n     469
Name: gearing_type, dtype: int64
******************************

In [872]:
df.gearing_type = df.gearing_type.str.strip("\n,")

# 31 Displacement

In [873]:
check_df("displacement")

column name :  displacement
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 3.12
Num_of_Nulls   :  496
\n1,598 cc\n    4761
\n999 cc\n      2438
\n1,398 cc\n    1314
\n1,399 cc\n     749
\n1,229 cc\n     677
                ...
\n122 cc\n         1
\n1,198 cc\n       1
\n1,195 cc\n       1
\n2,967 cc\n       1
\n1,800 cc\n       1
Name: displacement, Length: 78, dtype: int64
******************************

In [874]:
df.displacement.str.strip("\n cc").str.replace(",", "").astype(float).value_counts().sort_index(ascending=True).head(60)

1.0         36
2.0          2
54.0         1
122.0        1
139.0        4
140.0        1
160.0        6
890.0        1
898.0      351
899.0       11
900.0        4
929.0        5
973.0        1
995.0        2
996.0        1
997.0        4
998.0       72
999.0     2438
1000.0      40
1100.0       1
1149.0     288
1195.0       1
1197.0     353
1198.0       1
1199.0       3
1200.0      18
1229.0     677
1239.0       1
1248.0     110
1300.0       2
1333.0       1
1350.0       1
1364.0     102
1368.0       1
1369.0       1
1390.0       1
1395.0     320
1396.0       3
1397.0      11
1398.0    1314
1399.0     749
1400.0      90
1422.0     467
1461.0     595
1490.0     559
1495.0       2
1496.0       1
1498.0     196
1499.0       5
1500.0      50
1533.0       1
1568.0       1
1580.0       1
1584.0       1
1589.0       2
1596.0       4
1598.0    4761
1599.0       3
1600.0     130
1618.0     212
Name: displacement, dtype: int64

In [875]:
df.displacement = df.displacement.str.strip("\n cc").str.replace(",", "").astype(float)

In [876]:
df.rename(columns={"displacement":"engine_displacement_cc"}, inplace=True)

# 32 Cylinders

In [877]:
check_df("cylinders")

column name :  cylinders
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 35.68
Num_of_Nulls   :  5680
\n4\n    8105
NaN      5680
\n3\n    2104
\n5\n      22
\n6\n       3
\n8\n       2
\n2\n       2
\n1\n       1
Name: cylinders, dtype: int64
******************************

In [878]:
df.cylinders.str.strip("\n").value_counts(dropna=False)

4      8105
NaN    5680
3      2104
5        22
6         3
8         2
2         2
1         1
Name: cylinders, dtype: int64

In [879]:
df.cylinders = df.cylinders.str.strip("\n").astype(float)

# 33 Weight

In [880]:
check_df("weight")

column name :  weight
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 43.81
Num_of_Nulls   :  6974
NaN             6974
\n1,163 kg\n     574
\n1,360 kg\n     356
\n1,165 kg\n     301
\n1,335 kg\n     242
                ...
\n1,960 kg\n       1
\n1,258 kg\n       1
\n1,167 kg\n       1
\n1,331 kg\n       1
\n2,037 kg\n       1
Name: weight, Length: 435, dtype: int64
******************************

In [881]:
df.weight.str.strip("\n kg").str.replace(",", "")

0        1220
1        1255
2         NaN
3        1195
4         NaN
         ...
15914    1758
15915    1708
15916     NaN
15917    1758
15918    1685
Name: weight, Length: 15919, dtype: object

In [882]:
df.weight = df.weight.str.strip("\n kg").str.replace(",", "")

In [883]:
df.rename(columns={"weight":"weight_kg"}, inplace=True)

In [884]:
df.weight_kg = df.weight_kg.astype(float)

In [885]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             14895 non-null  float64
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   float64
 8   hp_kW                          15831 non-null  float64
 9   type                           15917 non-null  object
 10  previous_owners                9279 non-null   float64
 11  warranty                       4853 non-null   float64
 12  make                           15919 non-null  object
 13  model                          15919 non-null  object
 14  body_color                     15322 non-null  object
 15  paint_type                     10147 non-null  object
 16  body_color_original            12160 non-null  object
 17  upholstery                     12199 non-null  object
 18  nr_of_doors                    15707 non-null  float64
 19  nr_of_seats                    14942 non-null  float64
 20  gearing_type                   15919 non-null  object
 21  engine_displacement_cc         15423 non-null  float64
 22  cylinders                      10239 non-null  float64
 23  weight_kg                      8945 non-null   float64
 24  drive_chain                    9061 non-null   object
 25  fuel                           15919 non-null  object
 26  consumption                    14013 non-null  object
 27  co2_emission                   14111 non-null  object
 28  emission_class                 12898 non-null  object
 29  comfort&convenience            14999 non-null  object
 30  entertainment&media            14545 non-null  object
 31  extras                         12957 non-null  object
 32  safety_&_security              14937 non-null  object
 33  description                    15919 non-null  object
 34  emission_label                 3985 non-null   object
 35  gears                          11207 non-null  object
 36  country_version                7586 non-null   object
 37  electricity_consumption        137 non-null    object
 38  last_service_date              566 non-null    object
 39  other_fuel_types               880 non-null    object
 40  availability                   635 non-null    object
 41  last_timing_belt_service_date  16 non-null     object
 42  available_from                 272 non-null    object
dtypes: float64(12), object(31)
memory usage: 5.2+ MB

# 34 Drive chain

In [886]:
check_df("drive_chain")

column name :  drive_chain
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 43.08
Num_of_Nulls   :  6858
\nfront\n    8886
NaN          6858
\n4WD\n       171
\nrear\n        4
Name: drive_chain, dtype: int64
******************************

In [887]:
df.drive_chain.str.strip("\n").value_counts(dropna=False)

front    8886
NaN      6858
4WD       171
rear        4
Name: drive_chain, dtype: int64

In [888]:
df.drive_chain = df.drive_chain.str.strip("\n")

# 35 Fuel

In [889]:
check_df("fuel")

column name :  fuel
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
\n,Diesel (Particulate Filter),\n                                                                                  4315
\n,Super 95,\n                                                                                                     3338
\n,Gasoline,\n                                                                                                     3175
\n,Diesel,\n                                                                                                       2984
\n,Super 95 / Regular/Benzine 91,\n                                                                                 424
                                                                                                                   ...
\n,Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91,\n                                                          1
\n,Super Plus 98 / Super E10 95,\n                                                                                    1
\n,Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98,\n       1
\n,Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98,\n       1
\n,Super Plus 98 / Super 95 / Super Plus E10 98,\n                                                                    1
Name: fuel, Length: 77, dtype: int64
******************************

In [890]:
df.fuel.str.strip("\n,").value_counts()

Diesel (Particulate Filter)                                                                                  4315
Super 95                                                                                                     3338
Gasoline                                                                                                     3175
Diesel                                                                                                       2984
Super 95 / Regular/Benzine 91                                                                                 424
                                                                                                             ...
Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91                                                          1
Super Plus 98 / Super E10 95                                                                                    1
Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98       1
Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98       1
Super Plus 98 / Super 95 / Super Plus E10 98                                                                    1
Name: fuel, Length: 77, dtype: int64

In [891]:
df.fuel = df.fuel.str.strip("\n,")

In [892]:
# df.fuel.str.extract(r"(\w+\s?\w+\s?\w+\s?\w+|\w+)").value_counts(dropna=False)
df.fuel.str.extract(r"(\w+\s?\w+\s?\w+)").value_counts(dropna=False)

Diesel                  7299
Super 95                4368
Gasoline                3252
Regular                  503
Super E10 95             409
CNG                       36
LPG                       16
Super Plus 98             11
Liquid petroleum gas      10
Others                     6
Electric                   5
Super Plus E10             2
Biogas                     1
Domestic gas H             1
dtype: int64

In [893]:
df.fuel = df.fuel.str.extract(r"(\w+\s?\w+\s?\w+)")

In [894]:
benzine = ["Gsoline", "Super 95", "Regular", "Super E10 95", "Super Plus 98", "Super Plus E10 98", "Super Plus E10", "Others"]
lpg = ["LPG", "Liquid petroleum gas", "CNG", "Biogas", "Domestic gas H"]

In [895]:
def fueltype(x):
    if x in benzine:
        return "Benzine"
    elif x in lpg:
        return "LPG/CNG"
    else :
        return x

In [896]:
df.fuel.apply(fueltype).value_counts()

Diesel      7299
Benzine     5299
Gasoline    3252
LPG/CNG       64
Electric       5
Name: fuel, dtype: int64

In [897]:
df.fuel = df.fuel.apply(fueltype)

# 36 Consumption

In [898]:
check_df("consumption")

column name :  consumption
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 11.97
Num_of_Nulls   :  1906
NaN                                                                           1906
['3.9 l/100 km (comb)'],['4.1 l/100 km (city)'],['3.7 l/100 km (country)']     304
['4.2 l/100 km (comb)'],['5 l/100 km (city)'],['3.7 l/100 km (country)']       276
['5.4 l/100 km (comb)'],['6.8 l/100 km (city)'],['4.5 l/100 km (country)']     257
['3.8 l/100 km (comb)'],['4.3 l/100 km (city)'],['3.5 l/100 km (country)']     253
                                                                              ...
['4.2 l/100 km (comb)'],['5.3 l/100 km (city)'],['3.6 l/100 km (country)']       1
\n,5.1 l/100 km (comb),\n,6.4 l/100 km (city),\n,4.3 l/100 km (country),\n       1
['4.6 l/100 km (comb)'],['5.4 l/100 km (city)'],['6.7 l/100 km (country)']       1
\n,6.3 l/100 km (comb),\n,\n,\n                                                  1
\n,7.4 l/100 km (comb),\n,9.6 l/100 km (city),\n,6 l/100 km (country),\n         1
Name: consumption, Length: 882, dtype: int64
******************************

In [899]:
df.consumption.str.extract(r"(\d+\.\d+) l/100 km \(comb\)").astype(float)

         0
0      3.8
1      5.6
2      3.8
3      3.8
4      4.1
...    ...
15914  5.3
15915  7.4
15916  5.3
15917  5.3
15918  6.8

[15919 rows x 1 columns]

In [900]:
df["consumption_comb"] = df.consumption.str.extract(r"(\d+\.\d+) l/100 km \(comb\)").astype(float)

In [901]:
df.consumption.str.extract(r"(\d+\.\d+) l/100 km \(city\)").astype(float)

         0
0      4.3
1      7.1
2      4.4
3      4.3
4      4.6
...    ...
15914  6.2
15915  9.2
15916  6.2
15917  6.2
15918  8.7

[15919 rows x 1 columns]

In [902]:
df["consumption_city"] = df.consumption.str.extract(r"(\d+\.\d+) l/100 km \(city\)").astype(float)

In [903]:
df.consumption.str.extract(r"(\d+\.\d+) l/100 km \(country\)").astype(float)

         0
0      3.5
1      4.7
2      3.4
3      3.5
4      3.8
...    ...
15914  4.7
15915  6.3
15916  4.7
15917  4.7
15918  5.7

[15919 rows x 1 columns]

In [904]:
df["consumption_cuntry"] = df.consumption.str.extract(r"(\d+\.\d+) l/100 km \(country\)").astype(float)

In [905]:
df.drop(columns="consumption", inplace=True)

# 37 CO2 Emission

In [906]:
df.rename(columns={"co2_emission":"co2e_g"}, inplace=True)

In [907]:
check_df("co2e_g")

column name :  co2e_g
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 11.36
Num_of_Nulls   :  1808
NaN                          1808
\n120 g CO2/km (comb)\n       740
[],[],[]                      628
\n99 g CO2/km (comb)\n        545
\n97 g CO2/km (comb)\n        537
                             ...
\n14 g CO2/km (comb)\n          1
\n1,060 g CO2/km (comb)\n       1
\n51 g CO2/km (comb)\n          1
\n165 g CO2/km (comb)\n         1
\n193 g CO2/km (comb)\n         1
Name: co2e_g, Length: 124, dtype: int64
******************************

In [908]:
df.co2e_g = df.co2e_g.str.extract(r"(\d+\W?\d+) g")
df.co2e_g = df.co2e_g.str.replace(",", "").astype(float)

In [910]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_‚Ç¨                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             14895 non-null  float64
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   float64
 8   hp_kW                          15831 non-null  float64
 9   type                           15917 non-null  object
 10  previous_owners                9279 non-null   float64
 11  warranty                       4853 non-null   float64
 12  make                           15919 non-null  object
 13  model                          15919 non-null  object
 14  body_color                     15322 non-null  object
 15  paint_type                     10147 non-null  object
 16  body_color_original            12160 non-null  object
 17  upholstery                     12199 non-null  object
 18  nr_of_doors                    15707 non-null  float64
 19  nr_of_seats                    14942 non-null  float64
 20  gearing_type                   15919 non-null  object
 21  engine_displacement_cc         15423 non-null  float64
 22  cylinders                      10239 non-null  float64
 23  weight_kg                      8945 non-null   float64
 24  drive_chain                    9061 non-null   object
 25  fuel                           15919 non-null  object
 26  co2e_g                         13477 non-null  float64
 27  emission_class                 12898 non-null  object
 28  comfort&convenience            14999 non-null  object
 29  entertainment&media            14545 non-null  object
 30  extras                         12957 non-null  object
 31  safety_&_security              14937 non-null  object
 32  description                    15919 non-null  object
 33  emission_label                 3985 non-null   object
 34  gears                          11207 non-null  object
 35  country_version                7586 non-null   object
 36  electricity_consumption        137 non-null    object
 37  last_service_date              566 non-null    object
 38  other_fuel_types               880 non-null    object
 39  availability                   635 non-null    object
 40  last_timing_belt_service_date  16 non-null     object
 41  available_from                 272 non-null    object
 42  consumption_comb               12129 non-null  float64
 43  consumption_city               11880 non-null  float64
 44  consumption_cuntry             12554 non-null  float64
dtypes: float64(16), object(29)
memory usage: 5.5+ MB

# 37 Emission Class

In [911]:
check_df("emission_class")

column name :  emission_class
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 18.98
Num_of_Nulls   :  3021
\nEuro 6\n          10139
NaN                  3021
\nEuro 6d-TEMP\n     1845
[],[],[]              607
\nEuro 6c\n           127
\nEuro 5\n             78
\nEuro 6d\n            62
\nEuro 4\n             40
Name: emission_class, dtype: int64
******************************

In [912]:
df.emission_class.str.strip("[],\n").value_counts(dropna=False)

Euro 6          10139
NaN              3021
Euro 6d-TEMP     1845
                  607
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: emission_class, dtype: int64

In [913]:
df.emission_class.str.strip("[],\n").replace("", np.nan).value_counts(dropna=False)

Euro 6          10139
NaN              3628
Euro 6d-TEMP     1845
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: emission_class, dtype: int64

In [914]:
df.emission_class = df.emission_class.str.strip("[],\n").replace("", np.nan)

In [915]:
df.emission_class.value_counts(dropna=False)

Euro 6          10139
NaN              3628
Euro 6d-TEMP     1845
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: emission_class, dtype: int64

# 38 Comfort & Convenience

# 39 Entertainment & Media

In [916]:
check_df("entertainment&media")

column name :  entertainment&media
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 8.63
Num_of_Nulls   :  1374
NaN                                                                                                 1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                          1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                       982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                             783
On-board computer,Radio                                                                              487
                                                                                                    ...
Bluetooth,CD player,Digital radio,Hands-free equipment,Radio                                           1
CD player,Hands-free equipment,MP3,Radio,USB                                                           1
MP3,Radio,Sound system,USB                                                                             1
Bluetooth,MP3,On-board computer,Radio,Television,USB                                                   1
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,Television,USB       1
Name: entertainment&media, Length: 347, dtype: int64
******************************

# 40 Extras

In [917]:
check_df("extras")

column name :  extras
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 18.61
Num_of_Nulls   :  2962
Alloy wheels                                                                                               3245
NaN                                                                                                        2962
Alloy wheels,Touch screen                                                                                   697
Alloy wheels,Voice Control                                                                                  577
Alloy wheels,Touch screen,Voice Control                                                                     541
                                                                                                           ...
Alloy wheels,Catalytic Converter,Shift paddles,Sport package,Sport seats,Sport suspension,Voice Control       1
Alloy wheels,Catalytic Converter,Roof rack,Sport package,Sport seats,Trailer hitch                            1
Alloy wheels,Catalytic Converter,Ski bag,Sport package,Voice Control                                          1
Catalytic Converter,Roof rack,Sport seats,Sport suspension                                                    1
Alloy wheels,Shift paddles,Ski bag,Sport seats,Sport suspension,Touch screen,Voice Control                    1
Name: extras, Length: 660, dtype: int64
******************************

# 41 Safety & Security

In [918]:
df.rename(columns={"safety_&_security":"safety&security"}, inplace=True)

In [919]:
check_df("safety&security")

column name :  safety&security
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 6.17
Num_of_Nulls   :  982
NaN                                                                                                                                                                                                                                                                                                                                                               982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                      538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                                 480
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                                                                                                275
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                           272
                                                                                                                                                                                                                                                                                                                                                                 ...
ABS,Central door lock,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag                                                                                                                                                                                                                                              1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                 1
ABS,Adaptive Cruise Control,Alarm system,Central door lock,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Power steering,Tire pressure monitoring system,Traction control                                                                                                                                                  1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,LED Headlights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traffic sign recognition      1
Name: safety&security, Length: 4444, dtype: int64
******************************

In [920]:
df.columns

Index(['url', 'short_description', 'body_type', 'price_‚Ç¨', 'vat', 'km',
       'registration', 'prev_owner', 'hp_kW', 'type', 'previous_owners',
       'warranty', 'make', 'model', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'nr_of_doors', 'nr_of_seats',
       'gearing_type', 'engine_displacement_cc', 'cylinders', 'weight_kg',
       'drive_chain', 'fuel', 'co2e_g', 'emission_class',
       'comfort&convenience', 'entertainment&media', 'extras',
       'safety&security', 'description', 'emission_label', 'gears',
       'country_version', 'electricity_consumption', 'last_service_date',
       'other_fuel_types', 'availability', 'last_timing_belt_service_date',
       'available_from', 'consumption_comb', 'consumption_city',
       'consumption_cuntry'],
      dtype='object')

# 42 description

In [921]:
check_df("description")

column name :  description
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               636
\n,\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           30
\n,Fahrzeugbeschreibung, Sichern Sie sich diesen Renault Clio 1.6 TCE Energy Sport Trophy zum Top-Preis inklusive dem ,AUTOHERO-RUNDUM-SORGLOS-PAKET, ,Infos:, 1.Hand, deutsche Auslieferung, Unfallfrei, scheckheftgepflegt, ,Highlights, ,Audio-Navigationssystem R-Link Evolution mit Touchscreen und Carminat TomTom, ,Sportsitze , ,Sportfahrwerk, ,Scheinwerfer Full-LED ,Komfort, ,Geschwindigkeits-Regelanlage (Tempomat) , ,Klimaanlage, ,Einparkhilfe hinten, ,Multifunktionslenkrad (Sport/Leder) mit Schaltwippen/-tasten , ,Fensterheber elektr. mit Impulsgeber links/rechts vorn, ,Zentralverriegelung / Startanlage Handsfree Entry & Drive , ,Berganfahr-Assistent (HSA) ,Multimedia, ,Audiosystem: Radio R & GO (Bluetooth, DAB-Tuner), ,Bordcomputer, ,Freisprecheinrichtung Bluetooth , ,USB-Anschluss inkl. AUX-IN-Anschluss (Plug & Music) ,Licht und Sicht, ,Au√üenspiegel elektr. verstell- und heizbar , ,Licht- und Regensensor , ,Tagfahrlicht LED , ,Nebelscheinwerfer LED , ,Coming-Home-Lichtfunktion , ,Heckleuchten LED ,Sicherheit, ,Isofix-Aufnahmen f√ºr Kindersitz , ,Seitenairbag vorn, ,Wegfahrsperre, ,Differentialsperre, ,Bremsassistent , ,Elektron. Stabilit√§ts-Programm (ESP), ,Anti-Blockier-System (ABS), ,Anti-Submarining-Airbag im Fond, ,Airbag Fahrer-/Beifahrerseite , ,Differentialsperre , ,Reifendruck-Kontrollsystem , ,Untersteuerungskontrolle (USC) , ,Antischlupfregelung (ASR) ,Weiteres, ,Start/Stop-Anlage , ,Servolenkung geschwindigkeitsabh√§ngig, ,R.S. Drive (Fahrmodusschalter) , ,Gep√§ckraumabdeckung / Rollo , ,Heckdiffusor , ,LM-Felgen , ,Heckspoiler (Renault Sport) , ,Pedale Aluminium , ,Energier√ºckgewinnung (Energy Smart Management) , ,Elektr. Bremskraftverteilung , ,Reifen-Reparaturkit , ,Sitzbezug / Polsterung: Stoff , Ihr ,AUTOHERO-RUNDUM-SORGLOS-PAKET, beinhaltet:,Kostenlose Lieferung in Ihre N√§he,Optische & technische Aufbereitung,Mindestens 12 Monate g√ºltige HU und AU,1-Jahr-Premium-Garantie,Zulassung inklusive ,14-Tage-R√ºckgaberecht,Markenunabh√§ngige Inzahlungnahme ,Individuelle Finanzierungen zu fairen Konditionen, ,HIER GEHT ES ZUR 360¬∞ - ANSICHT DES FAHRZEUGES:,:,https://www.autohero.com/de/renault-clio-1-6-tce-energy-renault-sport-trophy/id/f7ca29bf-e005-453f-bbc9-8c6fe892dec6/, ,Haftungsausschluss,:,F√ºr Angaben vom Verk√§ufer, des Herstellers oder von Datenbankabfragen √ºbernimmt Autohero keine Haftung. √Ñnderungen, Zwischenverkauf und Irrt√ºmer sind vorbehalten.\n                                                                                                                                                           27
\nPosibilidad de prueba del veh√≠culo hasta 5 d√≠as. Consultar condiciones. PVP para particulares. Varias unidades y colores disponibles. Precios publicados para veh√≠culos industriales (furgonetas) v√°lidos para compradores aut√≥nomos o empresas, consultar condiciones para particulares. Las im√°genes y kil√≥metros pueden no corresponder con el modelo anunciado. Para confirmar p√≥ngase en contacto con nuestro departamento comercial. Consulta las excepcionales condiciones de financiaci√≥n que tenemos disponibles. Precio de venta final IVA y gastos de transferencia incluidos. Horario de atenci√≥n al cliente: Lunes a Viernes de 09:00 a 18:00.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 27
\nSichern Sie sich diesen RENAULT CLIO 1.2 LIMITED zum Top-Preis inklusive dem,AUTOHERO-RUNDUM-SORGLOS-PAKET, ,Infos:, 2.Hand, mindestens 12 Monate g√ºltige HU und AU, deutsche Ausf√ºhrung, unfallfrei , ,Highlights, ,Audio-Navigationssystem mit Touchscreen-Farbdisplay,Komfort, ,Klimaanlage , ,Multifunktionslenkrad in Leder , ,Berganfahr-Assistent (HSA), ,Fensterheber elektrisch vorn , ,Geschwindigkeits-Regelanlage (Tempomat) , ,Heckscheibe heizbar , ,Sitz vorn links h√∂henverstellbar, ,Sitz vorn rechts umklappbar , ,Stau-/Ablagefach im Laderaumboden , ,Zentralverriegelung mit Fernbedienung ,Multimedia, ,Radio R&GO, ,Bluetooth Freisprechanlage , ,USB-/AUX-Schnittstelle , ,Bordcomputer, ,Licht und Sicht, ,Tagfahrlicht LED , ,Au√üenspiegel elektrisch verstell- und heizbar,Sicherheit, ,Airbag f√ºr Fahrer und Beifahrer, ,Beifahrerairbag deaktivierbar , ,Seitenairbags vorn , ,Kopfairbagsystem, ,Anti-Blockier-System (ABS), ,Elektronische Bremskraftverteilung , ,Elektronische Stabilit√§ts-Programm (ESP) , ,Reifen-Reparaturkit , ,Reifendruck-Kontrollsystem , ,Untersteuerungskontrolle (USC) , ,ISOFIX Kindersitzverankerung ,Weiteres, ,Dachreling silber , ,Look-Paket Chrom (au√üen) , ,Look-Paket Grau (innen) , ,R&GO-Paket , ,Style-Paket , Ihr ,AUTOHERO-RUNDUM-SORGLOS-PAKET, beinhaltet:,Kostenlose Lieferung in Ihre N√§he,Optische & technische Aufbereitung,Mindestens 12 Monate g√ºltige HU und AU,1-Jahr-Premium-Garantie,Zulassung inklusive ,14-Tage-R√ºckgaberecht,Markenunabh√§ngige Inzahlungnahme ,Individuelle Finanzierungen zu fairen Konditionen, ,HIER GEHT ES ZUR 360¬∞ - ANSICHT DES FAHRZEUGES:,:,https://www.autohero.com/de/renault-clio-1-2-limited/id/30f99516-8785-47e7-a4a3-6cdac4d8e633/, ,Haftungsausschluss,:,F√ºr Angaben vom Verk√§ufer, des Herstellers oder von Datenbankabfragen √ºbernimmt Autohero keine Haftung. √Ñnderungen, Zwischenverkauf und Irrt√ºmer sind vorbehalten.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        27
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...
\nPratica¬†67374,Airbag fullsize per conducente e passeggero, Alzacristalli elettrici ant. e post. con funzione attivaz. a pressione, Assetto dinamico, Audi drive select, Inserti in micrometallic argento, Kit riparazione pneumatici, Pacchetto di navigazione, Piano di copertura del vano bagagli estraibile, Presa AUX-IN, Proiettori allo Xenon Plus con reg. aut. prof. fari, Lavafari, Rivestimenti dei sedili in tessuto, Serbatoio AdBlue, Sistema controllo pressione pneumatici, Sistema di ancoraggio ISOFIX e 3¬∞ punto di ancoraggio Top Tether sui sedili post. laterali, Sistema di informazioni per il conducente con display monocromatico, Tappetini anteriori e posteriori, Versione Business, Volante sportivo multifunzionale in pelle 3 razze, ABS, EBV (Ripartitore elettronico della forza frenante), Airbag laterali anteriori integrati negli schienali dei sedili, Airbag per la testa, Airbag per le ginocchia (lato conducente), Appoggiatesta anteriori (2) e posteriori (3) regolabili, Radio MMI plus, Interfaccia Bluetooth, Appoggiabraccia centrale anteriore, Cambio manuale, Cerchi in lega 7 J x 16" a 5 razze a stella, Chiusura centralizzata con telecomando, Regolatore di velocit√†, ESC - Sistema elettronico di controllo della stabilizzazione con bloccaggio trasversale elettronico, ASR - Dispositivo di controllo della trazione, EDS (Dispositivo antislittamento in partenza), Filtro anti particolato, Cinture di sicurezza con pretensionatore, Specchietti retrovisivi esterni riscaldabili e ripiegabili elettricamente, Schienale del sedile posteriore ribaltabile (divisibile in rapporto 40:60 o ribaltabile completam.), Sistema di ausilio al parcheggio posteriore, Servosterzo elettromeccanico, Tergilunotto\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1

In [922]:
df.drop(columns="description", inplace=True)

# 42 Emission Label

In [923]:
check_df("emission_label")

column name :  emission_label
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 74.97
Num_of_Nulls   :  11934
NaN                   11934
\n4 (Green)\n          3553
\n1 (No sticker)\n      381
[],[],[]                 40
\n5 (Blue)\n              8
\n3 (Yellow)\n            2
\n2 (Red)\n               1
Name: emission_label, dtype: int64
******************************

In [924]:
df.drop(columns="emission_label", inplace=True)

# 43 Gears

In [925]:
check_df("gears")

column name :  gears
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 29.6
Num_of_Nulls   :  4712
\n6\n     5822
NaN       4712
\n5\n     3239
\n7\n     1908
\n8\n      224
\n9\n        6
\n1\n        2
\n3\n        2
\n4\n        2
\n2\n        1
\n50\n       1
Name: gears, dtype: int64
******************************

In [926]:
df.gears.str.strip("\n").value_counts(dropna=False)

6      5822
NaN    4712
5      3239
7      1908
8       224
9         6
1         2
3         2
4         2
2         1
50        1
Name: gears, dtype: int64

In [927]:
df.gears = df.gears.str.strip("\n").astype(float)

# 44 Country version

In [928]:
check_df("country_version")

column name :  country_version
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 52.35
Num_of_Nulls   :  8333
NaN                   8333
\nGermany\n           4502
\nItaly\n             1038
\nEuropean Union\n     507
\nNetherlands\n        464
\nSpain\n              325
\nBelgium\n            314
\nAustria\n            208
\nCzech Republic\n      52
\nPoland\n              49
\nFrance\n              38
\nDenmark\n             33
\nHungary\n             28
\nJapan\n                8
\nSlovakia\n             4
\nCroatia\n              4
\nSweden\n               3
\nRomania\n              2
\nBulgaria\n             2
\nLuxembourg\n           1
\nSwitzerland\n          1
\nSlovenia\n             1
\nEgypt\n                1
\nSerbia\n               1
Name: country_version, dtype: int64
******************************

In [929]:
df.country_version.str.strip("\n").value_counts(dropna=False)

NaN               8333
Germany           4502
Italy             1038
European Union     507
Netherlands        464
Spain              325
Belgium            314
Austria            208
Czech Republic      52
Poland              49
France              38
Denmark             33
Hungary             28
Japan                8
Slovakia             4
Croatia              4
Sweden               3
Romania              2
Bulgaria             2
Luxembourg           1
Switzerland          1
Slovenia             1
Egypt                1
Serbia               1
Name: country_version, dtype: int64

In [930]:
df.country_version = df.country_version.str.strip("\n")

# 45 electricity_consumption', 'last_service_date', 'other_fuel_types',       'availability', 'last_timing_belt_service_date', 'available_from',       'consumption_comb', 'consumption_city', 'consumption_cuntry'

In [931]:
check_df("electricity_consumption")

column name :  electricity_consumption
-+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+--+-+-
Per_of_Nulls   :  % 99.14
Num_of_Nulls   :  15782
NaN                        15782
\n0 kWh/100 km (comb)\n      137
Name: electricity_consumption, dtype: int64
******************************

In [932]:
df.drop(columns=['url', 'electricity_consumption', 'last_service_date', 'other_fuel_types',
       'availability', 'last_timing_belt_service_date', 'available_from'], inplace=True)

In [933]:
df.columns

Index(['short_description', 'body_type', 'price_‚Ç¨', 'vat', 'km',
       'registration', 'prev_owner', 'hp_kW', 'type', 'previous_owners',
       'warranty', 'make', 'model', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'nr_of_doors', 'nr_of_seats',
       'gearing_type', 'engine_displacement_cc', 'cylinders', 'weight_kg',
       'drive_chain', 'fuel', 'co2e_g', 'emission_class',
       'comfort&convenience', 'entertainment&media', 'extras',
       'safety&security', 'gears', 'country_version', 'consumption_comb',
       'consumption_city', 'consumption_cuntry'],
      dtype='object')

In [934]:
df

,short_description,body_type,price_‚Ç¨,vat,km,registration,prev_owner,hp_kW,type,previous_owners,...,emission_class,comfort&convenience,entertainment&media,extras,safety&security,gears,country_version,consumption_comb,consumption_city,consumption_cuntry
0,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013.0,2016.0,2.0,66.0,Used,2.0,...,Euro 6,"Air conditioning,Armrest,Automatic climate con...","Bluetooth,Hands-free equipment,On-board comput...","Alloy wheels,Catalytic Converter,Voice Control","ABS,Central door lock,Daytime running lights,D...",NaN,NaN,3.8,4.3,3.5
1,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000.0,2017.0,NaN,141.0,Used,NaN,...,Euro 6,"Air conditioning,Automatic climate control,Hil...","Bluetooth,Hands-free equipment,On-board comput...","Alloy wheels,Sport seats,Sport suspension,Voic...","ABS,Central door lock,Central door lock with r...",7.0,NaN,5.6,7.1,4.7
2,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640.0,VAT deductible,83450.0,2016.0,1.0,85.0,Used,1.0,...,Euro 6,"Air conditioning,Cruise control,Electrical sid...","MP3,On-board computer","Alloy wheels,Voice Control","ABS,Central door lock,Daytime running lights,D...",NaN,NaN,3.8,4.4,3.4
3,1.4 TDi Design S tronic,Sedans,14500.0,None,73000.0,2016.0,1.0,66.0,Used,1.0,...,Euro 6,"Air suspension,Armrest,Auxiliary heating,Elect...","Bluetooth,CD player,Hands-free equipment,MP3,O...","Alloy wheels,Sport seats,Voice Control","ABS,Alarm system,Central door lock with remote...",6.0,NaN,3.8,4.3,3.5
4,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790.0,None,16200.0,2016.0,1.0,66.0,Used,1.0,...,Euro 6,"Air conditioning,Armrest,Automatic climate con...","Bluetooth,CD player,Hands-free equipment,MP3,O...","Alloy wheels,Sport package,Sport suspension,Vo...","ABS,Central door lock,Driver-side airbag,Elect...",NaN,Germany,4.1,4.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,Blue dCi 200CV EDC Executive 4Control,Van,39950.0,VAT deductible,NaN,NaN,NaN,147.0,New,NaN,...,NaN,"Air conditioning,Automatic climate control,Cru...","Bluetooth,Digital radio,Hands-free equipment,O...","Alloy wheels,Touch screen","ABS,Central door lock,Central door lock with r...",6.0,NaN,5.3,6.2,4.7
15915,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885.0,VAT deductible,9900.0,2019.0,1.0,165.0,Used,1.0,...,NaN,"Air conditioning,Automatic climate control,Cru...","Bluetooth,Digital radio,Hands-free equipment,R...","Alloy wheels,Touch screen,Voice Control","ABS,Adaptive Cruise Control,Blind spot monitor...",7.0,Germany,7.4,9.2,6.3
15916,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875.0,VAT deductible,15.0,2019.0,1.0,146.0,Pre-registered,1.0,...,Euro 6d-TEMP,"Air conditioning,Armrest,Automatic climate con...","Bluetooth,Hands-free equipment,On-board comput...",Alloy wheels,"ABS,Adaptive Cruise Control,Blind spot monitor...",6.0,Austria,5.3,6.2,4.7
15917,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700.0,VAT deductible,10.0,2019.0,NaN,147.0,Pre-registered,NaN,...,Euro 6,"Air conditioning,Automatic climate control,Cru...","Bluetooth,Digital radio,Radio,USB","Alloy wheels,Touch screen","ABS,Blind spot monitor,Driver-side airbag,Elec...",6.0,NaN,5.3,6.2,4.7
15918,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999.0,VAT deductible,NaN,2019.0,1.0,165.0,Demonstration,1.0,...,Euro 6,"Air conditioning,Automatic climate control,Cru...",USB,"Alloy wheels,Touch screen","ABS,Blind spot monitor,Daytime running lights,...",NaN,Germany,6.8,8.7,5.7

In [935]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   short_description       15873 non-null  object
 1   body_type               15859 non-null  object
 2   price_‚Ç¨                 15919 non-null  float64
 3   vat                     11406 non-null  object
 4   km                      14895 non-null  float64
 5   registration            14322 non-null  float64
 6   prev_owner              9091 non-null   float64
 7   hp_kW                   15831 non-null  float64
 8   type                    15917 non-null  object
 9   previous_owners         9279 non-null   float64
 10  warranty                4853 non-null   float64
 11  make                    15919 non-null  object
 12  model                   15919 non-null  object
 13  body_color              15322 non-null  object
 14  paint_type              10147 non-null  object
 15  body_color_original     12160 non-null  object
 16  upholstery              12199 non-null  object
 17  nr_of_doors             15707 non-null  float64
 18  nr_of_seats             14942 non-null  float64
 19  gearing_type            15919 non-null  object
 20  engine_displacement_cc  15423 non-null  float64
 21  cylinders               10239 non-null  float64
 22  weight_kg               8945 non-null   float64
 23  drive_chain             9061 non-null   object
 24  fuel                    15919 non-null  object
 25  co2e_g                  13477 non-null  float64
 26  emission_class          12291 non-null  object
 27  comfort&convenience     14999 non-null  object
 28  entertainment&media     14545 non-null  object
 29  extras                  12957 non-null  object
 30  safety&security         14937 non-null  object
 31  gears                   11207 non-null  float64
 32  country_version         7586 non-null   object
 33  consumption_comb        12129 non-null  float64
 34  consumption_city        11880 non-null  float64
 35  consumption_cuntry      12554 non-null  float64
dtypes: float64(17), object(19)
memory usage: 4.4+ MB

In [936]:
df.km.value_counts(dropna=False)

10.0       1045
NaN        1024
1.0         367
5.0         170
50.0        148
           ...
67469.0       1
43197.0       1
10027.0       1
35882.0       1
57.0          1
Name: km, Length: 6690, dtype: int64

In [938]:
df.to_csv("cleaned_autoscout.csv", index=False)